// ═══════════════════════════════════════════════════════════════
// Schema.org Properties Registry
// Maps Schema.org types to their real properties for SEO
// ═══════════════════════════════════════════════════════════════

export interface SchemaProperty {
  name: string;
  required: boolean;
  description: string;
  example: string;
}

export const SCHEMA_PROPERTIES: Record<string, SchemaProperty[]> = {
  // ── Organization family ──
  Organization: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "Organization" },
    { name: "name", required: true, description: "Nome da organização", example: "Minha Empresa SA" },
    { name: "url", required: true, description: "URL do site oficial", example: "https://example.com" },
    { name: "logo", required: true, description: "URL do logotipo", example: "https://example.com/logo.png" },
    { name: "description", required: false, description: "Descrição da organização", example: "Empresa líder em..." },
    { name: "foundingDate", required: false, description: "Data de fundação", example: "2020-01-15" },
    { name: "founder", required: false, description: "Fundador(es)", example: "João Silva" },
    { name: "numberOfEmployees", required: false, description: "Número de funcionários", example: "50" },
    { name: "sameAs", required: false, description: "Perfis sociais (array)", example: "https://facebook.com/empresa" },
    { name: "contactPoint", required: false, description: "Telefone de contato", example: "+55 11 3333-4444" },
    { name: "email", required: false, description: "E-mail corporativo", example: "contato@empresa.com" },
    { name: "address", required: false, description: "Endereço da sede", example: "Av. Paulista, 1000" },
    { name: "areaServed", required: false, description: "Área de atuação", example: "Brasil" },
    { name: "knowsAbout", required: false, description: "Áreas de expertise", example: "SEO, Marketing Digital" },
  ],
  Corporation: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "Corporation" },
    { name: "name", required: true, description: "Razão social", example: "Empresa SA" },
    { name: "url", required: true, description: "URL do site", example: "https://example.com" },
    { name: "logo", required: true, description: "URL do logo", example: "https://example.com/logo.png" },
    { name: "tickerSymbol", required: false, description: "Ticker na bolsa", example: "EMPR3" },
    { name: "foundingDate", required: false, description: "Data de fundação", example: "2010-03-01" },
    { name: "numberOfEmployees", required: false, description: "Número de funcionários", example: "500" },
    { name: "sameAs", required: false, description: "Perfis oficiais", example: "https://linkedin.com/company/..." },
  ],
  NGO: [
    { name: "@type", required: true, description: "Tipo", example: "NGO" },
    { name: "name", required: true, description: "Nome da ONG", example: "Instituto Solidário" },
    { name: "url", required: true, description: "URL do site", example: "https://ong.org" },
    { name: "description", required: false, description: "Missão da organização", example: "Promover educação..." },
    { name: "foundingDate", required: false, description: "Data de fundação", example: "2015-06-10" },
    { name: "areaServed", required: false, description: "Área de atuação", example: "América Latina" },
  ],

  // ── LocalBusiness family ──
  LocalBusiness: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "LocalBusiness" },
    { name: "name", required: true, description: "Nome do negócio", example: "Minha Empresa" },
    { name: "image", required: true, description: "URL da imagem", example: "https://example.com/photo.jpg" },
    { name: "address", required: true, description: "Endereço completo (PostalAddress)", example: "Av. Brasil, 456" },
    { name: "telephone", required: true, description: "Telefone principal", example: "+55 11 3333-4444" },
    { name: "url", required: false, description: "URL do site", example: "https://example.com" },
    { name: "priceRange", required: false, description: "Faixa de preço", example: "$$" },
    { name: "openingHoursSpecification", required: false, description: "Horário de funcionamento", example: "Seg-Sex 08:00-18:00" },
    { name: "aggregateRating", required: false, description: "Avaliação média", example: "4.2" },
    { name: "geo", required: false, description: "Coordenadas (lat, lng)", example: "-23.5505, -46.6333" },
    { name: "areaServed", required: false, description: "Área de atendimento", example: "São Paulo" },
    { name: "paymentAccepted", required: false, description: "Formas de pagamento", example: "Dinheiro, Cartão, Pix" },
    { name: "currenciesAccepted", required: false, description: "Moedas aceitas", example: "BRL" },
  ],
  Restaurant: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "Restaurant" },
    { name: "name", required: true, description: "Nome do restaurante", example: "Pizzaria do João" },
    { name: "image", required: true, description: "Foto principal", example: "https://example.com/photo.jpg" },
    { name: "address", required: true, description: "Endereço completo", example: "Rua Principal, 123" },
    { name: "telephone", required: true, description: "Telefone", example: "+55 11 99999-0000" },
    { name: "servesCuisine", required: false, description: "Tipo de culinária", example: "Italiana" },
    { name: "priceRange", required: false, description: "Faixa de preço", example: "$$" },
    { name: "openingHoursSpecification", required: false, description: "Horário", example: "Seg-Sex 11:00-23:00" },
    { name: "aggregateRating", required: false, description: "Avaliação agregada", example: "4.5" },
    { name: "acceptsReservations", required: false, description: "Aceita reservas", example: "True" },
    { name: "menu", required: false, description: "URL do cardápio", example: "https://example.com/menu" },
    { name: "geo", required: false, description: "Coordenadas", example: "-23.5505, -46.6333" },
    { name: "hasMenu", required: false, description: "Cardápio estruturado", example: "Menu principal" },
  ],
  Dentist: [
    { name: "@type", required: true, description: "Tipo", example: "Dentist" },
    { name: "name", required: true, description: "Nome da clínica/dentista", example: "Dr. Sorriso" },
    { name: "address", required: true, description: "Endereço", example: "Rua da Saúde, 100" },
    { name: "telephone", required: true, description: "Telefone", example: "+55 11 3333-4444" },
    { name: "medicalSpecialty", required: false, description: "Especialidade", example: "Ortodontia" },
    { name: "openingHoursSpecification", required: false, description: "Horário", example: "Seg-Sex 08:00-18:00" },
    { name: "aggregateRating", required: false, description: "Avaliação", example: "4.8" },
    { name: "image", required: false, description: "Foto do consultório", example: "https://example.com/clinic.jpg" },
  ],
  Physician: [
    { name: "@type", required: true, description: "Tipo", example: "Physician" },
    { name: "name", required: true, description: "Nome do médico/clínica", example: "Dr. João Silva" },
    { name: "address", required: true, description: "Endereço", example: "Av. Médica, 200" },
    { name: "telephone", required: true, description: "Telefone", example: "+55 11 2222-3333" },
    { name: "medicalSpecialty", required: false, description: "Especialidade médica", example: "Cardiologia" },
    { name: "availableService", required: false, description: "Serviços oferecidos", example: "Consultas, Exames" },
    { name: "openingHoursSpecification", required: false, description: "Horário", example: "Seg-Sex 08:00-17:00" },
  ],
  MedicalBusiness: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "MedicalBusiness" },
    { name: "name", required: true, description: "Nome da clínica", example: "Clínica Saúde" },
    { name: "address", required: true, description: "Endereço", example: "Rua dos Médicos, 100" },
    { name: "telephone", required: true, description: "Telefone", example: "+55 11 3333-4444" },
    { name: "medicalSpecialty", required: false, description: "Especialidade", example: "Cardiologia" },
    { name: "openingHoursSpecification", required: false, description: "Horário", example: "Seg-Sex 08:00-18:00" },
    { name: "availableService", required: false, description: "Serviços disponíveis", example: "Consulta, Exame" },
    { name: "isAcceptingNewPatients", required: false, description: "Aceita novos pacientes", example: "True" },
  ],
  LegalService: [
    { name: "@type", required: true, description: "Tipo", example: "LegalService" },
    { name: "name", required: true, description: "Nome do escritório", example: "Silva & Associados" },
    { name: "address", required: true, description: "Endereço", example: "Av. Justiça, 500" },
    { name: "telephone", required: true, description: "Telefone", example: "+55 11 2222-3333" },
    { name: "areaServed", required: false, description: "Área de atuação geográfica", example: "São Paulo" },
    { name: "knowsAbout", required: false, description: "Áreas do direito", example: "Trabalhista, Civil, Tributário" },
    { name: "url", required: false, description: "URL do site", example: "https://escritorio.com" },
  ],
  FinancialService: [
    { name: "@type", required: true, description: "Tipo", example: "FinancialService" },
    { name: "name", required: true, description: "Nome", example: "Contabilidade ABC" },
    { name: "address", required: true, description: "Endereço", example: "Rua Financeira, 300" },
    { name: "telephone", required: false, description: "Telefone", example: "+55 11 4444-5555" },
    { name: "feesAndCommissionsSpecification", required: false, description: "Tabela de honorários", example: "A partir de R$ 200/mês" },
  ],
  AutoRepair: [
    { name: "@type", required: true, description: "Tipo", example: "AutoRepair" },
    { name: "name", required: true, description: "Nome da oficina", example: "Oficina do Zé" },
    { name: "address", required: true, description: "Endereço", example: "Rua dos Mecânicos, 75" },
    { name: "telephone", required: true, description: "Telefone", example: "+55 11 5555-6666" },
    { name: "openingHoursSpecification", required: false, description: "Horário", example: "Seg-Sab 08:00-18:00" },
    { name: "paymentAccepted", required: false, description: "Formas de pagamento", example: "Cartão, Pix" },
  ],
  BeautySalon: [
    { name: "@type", required: true, description: "Tipo", example: "BeautySalon" },
    { name: "name", required: true, description: "Nome do salão", example: "Salão Beleza" },
    { name: "address", required: true, description: "Endereço", example: "Rua da Beleza, 42" },
    { name: "telephone", required: true, description: "Telefone", example: "+55 11 7777-8888" },
    { name: "openingHoursSpecification", required: false, description: "Horário", example: "Seg-Sab 09:00-19:00" },
    { name: "priceRange", required: false, description: "Faixa de preço", example: "$$" },
  ],
  HealthClub: [
    { name: "@type", required: true, description: "Tipo", example: "HealthClub" },
    { name: "name", required: true, description: "Nome da academia", example: "Fitness Club" },
    { name: "address", required: true, description: "Endereço", example: "Rua dos Atletas, 50" },
    { name: "telephone", required: false, description: "Telefone", example: "+55 11 8888-9999" },
    { name: "openingHoursSpecification", required: false, description: "Horário", example: "Seg-Sab 06:00-22:00" },
    { name: "amenityFeature", required: false, description: "Comodidades", example: "Piscina, Sauna, Estacionamento" },
  ],
  LodgingBusiness: [
    { name: "@type", required: true, description: "Tipo", example: "LodgingBusiness" },
    { name: "name", required: true, description: "Nome do hotel/pousada", example: "Hotel Beira-Mar" },
    { name: "address", required: true, description: "Endereço", example: "Av. Praia, 1000" },
    { name: "telephone", required: true, description: "Telefone", example: "+55 11 1111-2222" },
    { name: "checkinTime", required: false, description: "Horário de check-in", example: "14:00" },
    { name: "checkoutTime", required: false, description: "Horário de check-out", example: "12:00" },
    { name: "starRating", required: false, description: "Classificação em estrelas", example: "4" },
    { name: "amenityFeature", required: false, description: "Comodidades", example: "Wi-Fi, Café da manhã" },
    { name: "numberOfRooms", required: false, description: "Número de quartos", example: "50" },
  ],
  RealEstateAgent: [
    { name: "@type", required: true, description: "Tipo", example: "RealEstateAgent" },
    { name: "name", required: true, description: "Nome da imobiliária", example: "Imobiliária XYZ" },
    { name: "address", required: true, description: "Endereço", example: "Av. Central, 800" },
    { name: "telephone", required: false, description: "Telefone", example: "+55 11 3333-4444" },
    { name: "areaServed", required: false, description: "Região de atuação", example: "Zona Sul de SP" },
  ],
  HomeAndConstructionBusiness: [
    { name: "@type", required: true, description: "Tipo", example: "HomeAndConstructionBusiness" },
    { name: "name", required: true, description: "Nome", example: "Reparos Já" },
    { name: "address", required: true, description: "Endereço", example: "Rua da Construção, 100" },
    { name: "areaServed", required: false, description: "Área atendida", example: "Grande São Paulo" },
    { name: "telephone", required: false, description: "Telefone", example: "+55 11 6666-7777" },
  ],
  SportsActivityLocation: [
    { name: "@type", required: true, description: "Tipo", example: "SportsActivityLocation" },
    { name: "name", required: true, description: "Nome do local", example: "Arena Esportiva" },
    { name: "address", required: true, description: "Endereço", example: "Rua do Esporte, 200" },
    { name: "sport", required: false, description: "Esporte praticado", example: "Futebol, Tênis" },
    { name: "openingHoursSpecification", required: false, description: "Horário", example: "Todos os dias 06:00-22:00" },
  ],

  // ── Person ──
  Person: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "Person" },
    { name: "name", required: true, description: "Nome completo", example: "João Silva" },
    { name: "jobTitle", required: false, description: "Cargo / Profissão", example: "CEO" },
    { name: "worksFor", required: false, description: "Empresa onde trabalha", example: "Minha Empresa" },
    { name: "alumniOf", required: false, description: "Formação acadêmica", example: "USP" },
    { name: "knowsAbout", required: false, description: "Áreas de expertise", example: "SEO, Marketing Digital" },
    { name: "image", required: false, description: "Foto da pessoa", example: "https://example.com/photo.jpg" },
    { name: "sameAs", required: false, description: "Perfis sociais", example: "https://linkedin.com/in/joao" },
    { name: "email", required: false, description: "E-mail", example: "joao@empresa.com" },
    { name: "url", required: false, description: "Website pessoal", example: "https://joaosilva.com" },
    { name: "description", required: false, description: "Bio resumida", example: "Especialista em SEO com 10 anos..." },
    { name: "award", required: false, description: "Prêmios recebidos", example: "Melhor Profissional SEO 2024" },
  ],

  // ── Product family ──
  Product: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "Product" },
    { name: "name", required: true, description: "Nome do produto", example: "Produto Premium" },
    { name: "image", required: true, description: "Imagem do produto", example: "https://example.com/prod.jpg" },
    { name: "description", required: true, description: "Descrição detalhada", example: "O melhor produto..." },
    { name: "sku", required: false, description: "SKU / Código", example: "PROD-001" },
    { name: "gtin", required: false, description: "EAN / GTIN", example: "7891234567890" },
    { name: "brand", required: false, description: "Marca", example: "MinhaMarca" },
    { name: "offers", required: false, description: "Preço (Offer)", example: "R$ 99,90" },
    { name: "aggregateRating", required: false, description: "Avaliação média", example: "4.7" },
    { name: "review", required: false, description: "Reviews", example: "142 avaliações" },
    { name: "color", required: false, description: "Cor", example: "Azul" },
    { name: "material", required: false, description: "Material", example: "Algodão" },
    { name: "weight", required: false, description: "Peso", example: "500g" },
    { name: "category", required: false, description: "Categoria", example: "Eletrônicos" },
  ],
  IndividualProduct: [
    { name: "@type", required: true, description: "Tipo", example: "IndividualProduct" },
    { name: "name", required: true, description: "Nome do produto", example: "Produto Único" },
    { name: "serialNumber", required: false, description: "Número de série", example: "SN-12345" },
    { name: "sku", required: false, description: "SKU", example: "IND-001" },
    { name: "description", required: false, description: "Descrição", example: "Item exclusivo..." },
  ],
  ProductGroup: [
    { name: "@type", required: true, description: "Tipo", example: "ProductGroup" },
    { name: "name", required: true, description: "Nome da categoria", example: "Camisetas" },
    { name: "description", required: false, description: "Descrição do grupo", example: "Todas as camisetas" },
    { name: "hasVariant", required: false, description: "Variantes", example: "P, M, G, GG" },
    { name: "productGroupID", required: false, description: "ID do grupo", example: "CAT-CAMISETAS" },
    { name: "variesBy", required: false, description: "Varia por", example: "size, color" },
  ],
  Vehicle: [
    { name: "@type", required: true, description: "Tipo", example: "Vehicle" },
    { name: "name", required: true, description: "Modelo do veículo", example: "Honda Civic 2024" },
    { name: "brand", required: false, description: "Marca", example: "Honda" },
    { name: "model", required: false, description: "Modelo", example: "Civic" },
    { name: "vehicleModelDate", required: false, description: "Ano", example: "2024" },
    { name: "mileageFromOdometer", required: false, description: "Quilometragem", example: "15000 km" },
    { name: "fuelType", required: false, description: "Combustível", example: "Flex" },
    { name: "vehicleTransmission", required: false, description: "Câmbio", example: "Automático" },
    { name: "offers", required: false, description: "Preço", example: "R$ 120.000" },
  ],

  // ── Service ──
  Service: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "Service" },
    { name: "name", required: true, description: "Nome do serviço", example: "Consultoria SEO" },
    { name: "description", required: true, description: "Descrição do serviço", example: "Consultoria completa..." },
    { name: "provider", required: false, description: "Provedor (Organization)", example: "Minha Empresa" },
    { name: "areaServed", required: false, description: "Área geográfica atendida", example: "Brasil" },
    { name: "serviceType", required: false, description: "Tipo/Categoria do serviço", example: "Consultoria" },
    { name: "offers", required: false, description: "Preço (Offer)", example: "A partir de R$ 500" },
    { name: "serviceOutput", required: false, description: "Resultado do serviço", example: "Relatório técnico" },
    { name: "termsOfService", required: false, description: "Termos de serviço", example: "https://example.com/termos" },
    { name: "award", required: false, description: "Prêmios/Certificações", example: "ISO 9001" },
  ],
  ProfessionalService: [
    { name: "@type", required: true, description: "Tipo", example: "ProfessionalService" },
    { name: "name", required: true, description: "Nome", example: "Consultoria ABC" },
    { name: "address", required: true, description: "Endereço", example: "Rua Comercial, 200" },
    { name: "telephone", required: false, description: "Telefone", example: "+55 11 5555-6666" },
    { name: "priceRange", required: false, description: "Faixa de preço", example: "$$$" },
    { name: "knowsAbout", required: false, description: "Especialidades", example: "Consultoria empresarial" },
  ],
  FinancialProduct: [
    { name: "@type", required: true, description: "Tipo", example: "FinancialProduct" },
    { name: "name", required: true, description: "Nome do produto financeiro", example: "CDB 120% CDI" },
    { name: "description", required: false, description: "Descrição", example: "Investimento de renda fixa..." },
    { name: "interestRate", required: false, description: "Taxa de juros", example: "120% CDI" },
    { name: "annualPercentageRate", required: false, description: "Taxa anual", example: "13.5%" },
  ],

  // ── Place family ──
  Place: [
    { name: "@type", required: true, description: "Tipo Schema.org", example: "Place" },
    { name: "name", required: true, description: "Nome do local", example: "Centro de SP" },
    { name: "address", required: false, description: "Endereço", example: "Av. Paulista, 1000" },
    { name: "geo", required: false, description: "Coordenadas", example: "-23.56, -46.65" },
    { name: "telephone", required: false, description: "Telefone", example: "+55 11 1111-2222" },
    { name: "hasMap", required: false, description: "URL do mapa", example: "https://maps.google.com/..." },
  ],
  PostalAddress: [
    { name: "@type", required: true, description: "Tipo", example: "PostalAddress" },
    { name: "streetAddress", required: true, description: "Rua e número", example: "Rua Principal, 123" },
    { name: "addressLocality", required: true, description: "Cidade", example: "São Paulo" },
    { name: "addressRegion", required: true, description: "Estado", example: "SP" },
    { name: "postalCode", required: false, description: "CEP", example: "01234-567" },
    { name: "addressCountry", required: false, description: "País", example: "BR" },
  ],
  City: [
    { name: "@type", required: true, description: "Tipo", example: "City" },
    { name: "name", required: true, description: "Nome da cidade", example: "São Paulo" },
    { name: "containedInPlace", required: false, description: "Estado/País", example: "São Paulo, Brasil" },
    { name: "geo", required: false, description: "Coordenadas", example: "-23.5505, -46.6333" },
  ],

  // ── WebSite / WebPage ──
  WebSite: [
    { name: "@type", required: true, description: "Tipo", example: "WebSite" },
    { name: "name", required: true, description: "Nome do site", example: "Meu Site" },
    { name: "url", required: true, description: "URL", example: "https://example.com" },
    { name: "potentialAction", required: false, description: "SearchAction (busca interna)", example: "Busca interna" },
    { name: "inLanguage", required: false, description: "Idioma principal", example: "pt-BR" },
    { name: "publisher", required: false, description: "Publicador (Organization)", example: "Minha Empresa" },
  ],
  WebPage: [
    { name: "@type", required: true, description: "Tipo", example: "WebPage" },
    { name: "name", required: true, description: "Título da página", example: "Sobre Nós" },
    { name: "url", required: true, description: "URL", example: "https://example.com/sobre" },
    { name: "description", required: false, description: "Meta description", example: "Conheça nossa empresa..." },
    { name: "breadcrumb", required: false, description: "Breadcrumb trail", example: "Home > Sobre" },
    { name: "lastReviewed", required: false, description: "Última revisão", example: "2024-12-01" },
  ],
  AboutPage: [
    { name: "@type", required: true, description: "Tipo", example: "AboutPage" },
    { name: "name", required: true, description: "Título", example: "Sobre Nós" },
    { name: "url", required: true, description: "URL", example: "https://example.com/sobre" },
    { name: "description", required: false, description: "Descrição", example: "Conheça nossa história..." },
  ],
  ContactPage: [
    { name: "@type", required: true, description: "Tipo", example: "ContactPage" },
    { name: "name", required: true, description: "Título", example: "Contato" },
    { name: "url", required: true, description: "URL", example: "https://example.com/contato" },
  ],
  FAQPage: [
    { name: "@type", required: true, description: "Tipo", example: "FAQPage" },
    { name: "name", required: true, description: "Título da página FAQ", example: "Perguntas Frequentes" },
    { name: "url", required: false, description: "URL", example: "https://example.com/faq" },
    { name: "mainEntity", required: false, description: "Perguntas (array de Question)", example: "[Question...]" },
  ],
  CollectionPage: [
    { name: "@type", required: true, description: "Tipo", example: "CollectionPage" },
    { name: "name", required: true, description: "Nome da coleção", example: "Portfólio" },
    { name: "url", required: true, description: "URL", example: "https://example.com/portfolio" },
    { name: "description", required: false, description: "Descrição", example: "Nossos melhores trabalhos..." },
  ],
  ProfilePage: [
    { name: "@type", required: true, description: "Tipo", example: "ProfilePage" },
    { name: "name", required: true, description: "Nome do perfil", example: "Perfil - João Silva" },
    { name: "url", required: true, description: "URL", example: "https://example.com/joao" },
    { name: "mainEntity", required: false, description: "Pessoa do perfil", example: "Person: João Silva" },
  ],
  SearchResultsPage: [
    { name: "@type", required: true, description: "Tipo", example: "SearchResultsPage" },
    { name: "name", required: true, description: "Título", example: "Resultados de Busca" },
    { name: "url", required: true, description: "URL", example: "https://example.com/busca" },
  ],
  SiteNavigationElement: [
    { name: "@type", required: true, description: "Tipo", example: "SiteNavigationElement" },
    { name: "name", required: true, description: "Nome do menu", example: "Menu Principal" },
    { name: "url", required: false, description: "URL", example: "https://example.com/#nav" },
  ],
  ImageGallery: [
    { name: "@type", required: true, description: "Tipo", example: "ImageGallery" },
    { name: "name", required: true, description: "Nome da galeria", example: "Galeria de Projetos" },
    { name: "url", required: false, description: "URL", example: "https://example.com/galeria" },
  ],

  // ── Review / Rating ──
  Review: [
    { name: "@type", required: true, description: "Tipo", example: "Review" },
    { name: "reviewBody", required: true, description: "Texto da avaliação", example: "Excelente serviço!" },
    { name: "author", required: true, description: "Autor (Person)", example: "Maria Silva" },
    { name: "reviewRating", required: false, description: "Nota (Rating)", example: "5" },
    { name: "datePublished", required: false, description: "Data", example: "2024-01-15" },
    { name: "itemReviewed", required: false, description: "Item avaliado", example: "Produto Premium" },
  ],
  UserReview: [
    { name: "@type", required: true, description: "Tipo", example: "UserReview" },
    { name: "reviewBody", required: true, description: "Texto do depoimento", example: "Recomendo muito!" },
    { name: "author", required: true, description: "Autor", example: "Cliente XYZ" },
    { name: "reviewRating", required: false, description: "Nota", example: "5" },
  ],
  AggregateRating: [
    { name: "@type", required: true, description: "Tipo", example: "AggregateRating" },
    { name: "ratingValue", required: true, description: "Nota média", example: "4.5" },
    { name: "reviewCount", required: true, description: "Nº de avaliações", example: "142" },
    { name: "bestRating", required: false, description: "Nota máxima", example: "5" },
    { name: "worstRating", required: false, description: "Nota mínima", example: "1" },
  ],
  Rating: [
    { name: "@type", required: true, description: "Tipo", example: "Rating" },
    { name: "ratingValue", required: true, description: "Nota", example: "4.5" },
    { name: "bestRating", required: false, description: "Nota máxima", example: "5" },
    { name: "worstRating", required: false, description: "Nota mínima", example: "1" },
  ],

  // ── Event ──
  Event: [
    { name: "@type", required: true, description: "Tipo", example: "Event" },
    { name: "name", required: true, description: "Nome do evento", example: "Conferência SEO 2025" },
    { name: "startDate", required: true, description: "Data de início", example: "2025-03-15T09:00" },
    { name: "endDate", required: false, description: "Data de término", example: "2025-03-16T18:00" },
    { name: "location", required: false, description: "Local (Place)", example: "Centro de Convenções SP" },
    { name: "description", required: false, description: "Descrição", example: "O maior evento de SEO..." },
    { name: "organizer", required: false, description: "Organizador", example: "Minha Empresa" },
    { name: "offers", required: false, description: "Ingressos (Offer)", example: "R$ 500" },
    { name: "image", required: false, description: "Banner do evento", example: "https://example.com/event.jpg" },
    { name: "eventStatus", required: false, description: "Status", example: "EventScheduled" },
    { name: "eventAttendanceMode", required: false, description: "Modo", example: "OfflineEventAttendanceMode" },
    { name: "performer", required: false, description: "Palestrantes", example: "João Silva" },
  ],
  BusinessEvent: [{ name: "@type", required: true, description: "Tipo", example: "BusinessEvent" }, { name: "name", required: true, description: "Nome", example: "Workshop de Vendas" }, { name: "startDate", required: true, description: "Data", example: "2025-04-01T14:00" }],
  EducationEvent: [{ name: "@type", required: true, description: "Tipo", example: "EducationEvent" }, { name: "name", required: true, description: "Nome", example: "Aula Magna" }, { name: "startDate", required: true, description: "Data", example: "2025-02-15T10:00" }],
  MusicEvent: [{ name: "@type", required: true, description: "Tipo", example: "MusicEvent" }, { name: "name", required: true, description: "Nome", example: "Show ao Vivo" }, { name: "startDate", required: true, description: "Data", example: "2025-06-20T20:00" }, { name: "performer", required: false, description: "Artista", example: "Banda XYZ" }],

  // ── Article family ──
  Article: [
    { name: "@type", required: true, description: "Tipo", example: "Article" },
    { name: "headline", required: true, description: "Título do artigo", example: "Como fazer SEO em 2025" },
    { name: "author", required: true, description: "Autor (Person)", example: "João Silva" },
    { name: "datePublished", required: true, description: "Data de publicação", example: "2025-01-10" },
    { name: "dateModified", required: false, description: "Última atualização", example: "2025-01-15" },
    { name: "image", required: false, description: "Imagem de destaque", example: "https://example.com/article.jpg" },
    { name: "publisher", required: false, description: "Publicador (Organization)", example: "Minha Empresa" },
    { name: "description", required: false, description: "Resumo", example: "Guia completo de SEO..." },
    { name: "wordCount", required: false, description: "Nº de palavras", example: "2500" },
    { name: "inLanguage", required: false, description: "Idioma", example: "pt-BR" },
    { name: "keywords", required: false, description: "Palavras-chave", example: "SEO, Google, 2025" },
  ],
  BlogPosting: [
    { name: "@type", required: true, description: "Tipo", example: "BlogPosting" },
    { name: "headline", required: true, description: "Título", example: "Dicas de SEO" },
    { name: "author", required: true, description: "Autor", example: "Maria Silva" },
    { name: "datePublished", required: true, description: "Data", example: "2025-01-20" },
    { name: "image", required: false, description: "Imagem", example: "https://example.com/blog.jpg" },
    { name: "publisher", required: false, description: "Blog/Site", example: "Blog da Empresa" },
  ],
  NewsArticle: [
    { name: "@type", required: true, description: "Tipo", example: "NewsArticle" },
    { name: "headline", required: true, description: "Manchete", example: "Google anuncia..." },
    { name: "author", required: true, description: "Autor/Jornalista", example: "Pedro Santos" },
    { name: "datePublished", required: true, description: "Data", example: "2025-01-25" },
    { name: "publisher", required: false, description: "Veículo", example: "Portal de Notícias" },
  ],

  // ── Offer / Commerce ──
  Offer: [
    { name: "@type", required: true, description: "Tipo", example: "Offer" },
    { name: "price", required: true, description: "Preço", example: "99.90" },
    { name: "priceCurrency", required: true, description: "Moeda", example: "BRL" },
    { name: "availability", required: false, description: "Disponibilidade", example: "InStock" },
    { name: "url", required: false, description: "URL da oferta", example: "https://example.com/produto" },
    { name: "validFrom", required: false, description: "Válida a partir de", example: "2025-01-01" },
    { name: "validThrough", required: false, description: "Válida até", example: "2025-12-31" },
    { name: "seller", required: false, description: "Vendedor", example: "Minha Empresa" },
    { name: "itemCondition", required: false, description: "Condição", example: "NewCondition" },
  ],
  AggregateOffer: [
    { name: "@type", required: true, description: "Tipo", example: "AggregateOffer" },
    { name: "lowPrice", required: true, description: "Menor preço", example: "49.90" },
    { name: "highPrice", required: true, description: "Maior preço", example: "199.90" },
    { name: "priceCurrency", required: true, description: "Moeda", example: "BRL" },
    { name: "offerCount", required: false, description: "Nº de ofertas", example: "5" },
  ],
  PriceSpecification: [
    { name: "@type", required: true, description: "Tipo", example: "PriceSpecification" },
    { name: "price", required: true, description: "Preço", example: "99.90" },
    { name: "priceCurrency", required: true, description: "Moeda", example: "BRL" },
    { name: "billingDuration", required: false, description: "Duração do billing", example: "P1M (mensal)" },
  ],
  OfferShippingDetails: [
    { name: "@type", required: true, description: "Tipo", example: "OfferShippingDetails" },
    { name: "shippingRate", required: false, description: "Valor do frete", example: "R$ 15,00" },
    { name: "deliveryTime", required: false, description: "Prazo de entrega", example: "3-5 dias úteis" },
    { name: "shippingDestination", required: false, description: "Destino", example: "Brasil" },
  ],

  // ── Creative Works ──
  SoftwareApplication: [
    { name: "@type", required: true, description: "Tipo", example: "SoftwareApplication" },
    { name: "name", required: true, description: "Nome do software", example: "Meu App" },
    { name: "operatingSystem", required: false, description: "SO compatível", example: "Android, iOS" },
    { name: "applicationCategory", required: false, description: "Categoria", example: "BusinessApplication" },
    { name: "offers", required: false, description: "Preço", example: "Grátis" },
    { name: "aggregateRating", required: false, description: "Avaliação", example: "4.5" },
  ],
  VideoObject: [
    { name: "@type", required: true, description: "Tipo", example: "VideoObject" },
    { name: "name", required: true, description: "Título do vídeo", example: "Tutorial SEO" },
    { name: "description", required: true, description: "Descrição", example: "Aprenda SEO do zero..." },
    { name: "thumbnailUrl", required: true, description: "URL da thumbnail", example: "https://example.com/thumb.jpg" },
    { name: "uploadDate", required: true, description: "Data de upload", example: "2025-01-10" },
    { name: "duration", required: false, description: "Duração (ISO 8601)", example: "PT15M30S" },
    { name: "contentUrl", required: false, description: "URL do vídeo", example: "https://example.com/video.mp4" },
    { name: "embedUrl", required: false, description: "URL para embed", example: "https://youtube.com/embed/..." },
  ],
  ImageObject: [
    { name: "@type", required: true, description: "Tipo", example: "ImageObject" },
    { name: "name", required: true, description: "Título da imagem", example: "Foto do produto" },
    { name: "contentUrl", required: true, description: "URL da imagem", example: "https://example.com/img.jpg" },
    { name: "caption", required: false, description: "Legenda", example: "Vista frontal do produto" },
    { name: "width", required: false, description: "Largura", example: "1200" },
    { name: "height", required: false, description: "Altura", example: "800" },
  ],
  HowTo: [
    { name: "@type", required: true, description: "Tipo", example: "HowTo" },
    { name: "name", required: true, description: "Título", example: "Como fazer SEO" },
    { name: "description", required: false, description: "Descrição", example: "Guia passo a passo..." },
    { name: "step", required: false, description: "Passos (array)", example: "1. Pesquisar palavras-chave..." },
    { name: "totalTime", required: false, description: "Tempo total", example: "PT2H" },
    { name: "estimatedCost", required: false, description: "Custo estimado", example: "R$ 0 (gratuito)" },
  ],
  Recipe: [
    { name: "@type", required: true, description: "Tipo", example: "Recipe" },
    { name: "name", required: true, description: "Nome da receita", example: "Bolo de Cenoura" },
    { name: "author", required: true, description: "Autor", example: "Chef Maria" },
    { name: "image", required: true, description: "Foto do prato", example: "https://example.com/bolo.jpg" },
    { name: "prepTime", required: false, description: "Tempo de preparo", example: "PT30M" },
    { name: "cookTime", required: false, description: "Tempo de cozimento", example: "PT45M" },
    { name: "recipeIngredient", required: false, description: "Ingredientes", example: "2 cenouras, 3 ovos..." },
    { name: "recipeInstructions", required: false, description: "Modo de preparo", example: "1. Bata os ingredientes..." },
    { name: "recipeYield", required: false, description: "Rendimento", example: "8 porções" },
    { name: "recipeCategory", required: false, description: "Categoria", example: "Sobremesa" },
    { name: "recipeCuisine", required: false, description: "Culinária", example: "Brasileira" },
    { name: "nutrition", required: false, description: "Info nutricional", example: "250 kcal por porção" },
  ],
  Course: [
    { name: "@type", required: true, description: "Tipo", example: "Course" },
    { name: "name", required: true, description: "Nome do curso", example: "SEO Avançado" },
    { name: "description", required: true, description: "Descrição", example: "Domine SEO técnico..." },
    { name: "provider", required: false, description: "Instituição", example: "Academia Digital" },
    { name: "offers", required: false, description: "Preço", example: "R$ 997" },
    { name: "hasCourseInstance", required: false, description: "Turma", example: "Turma 2025.1" },
  ],

  // ── Intangible types ──
  Brand: [
    { name: "@type", required: true, description: "Tipo", example: "Brand" },
    { name: "name", required: true, description: "Nome da marca", example: "MinhaMarca" },
    { name: "logo", required: false, description: "Logo da marca", example: "https://example.com/logo.png" },
    { name: "slogan", required: false, description: "Slogan", example: "Inovação que transforma" },
    { name: "url", required: false, description: "URL da marca", example: "https://minhamarca.com" },
  ],
  Audience: [
    { name: "@type", required: true, description: "Tipo", example: "Audience" },
    { name: "audienceType", required: true, description: "Tipo de público", example: "Empreendedores" },
    { name: "geographicArea", required: false, description: "Região", example: "Brasil" },
  ],
  PeopleAudience: [
    { name: "@type", required: true, description: "Tipo", example: "PeopleAudience" },
    { name: "audienceType", required: true, description: "Tipo de público", example: "Jovens 18-25" },
    { name: "requiredGender", required: false, description: "Gênero", example: "Todos" },
    { name: "suggestedAge", required: false, description: "Faixa etária", example: "18-35" },
  ],
  BusinessAudience: [
    { name: "@type", required: true, description: "Tipo", example: "BusinessAudience" },
    { name: "audienceType", required: true, description: "Tipo de empresas", example: "PMEs" },
    { name: "numberOfEmployees", required: false, description: "Porte", example: "10-50 funcionários" },
  ],
  DefinedTerm: [
    { name: "@type", required: true, description: "Tipo", example: "DefinedTerm" },
    { name: "name", required: true, description: "Termo", example: "SEO On-Page" },
    { name: "description", required: false, description: "Definição", example: "Otimização dentro da página..." },
    { name: "inDefinedTermSet", required: false, description: "Vocabulário", example: "Glossário de Marketing" },
  ],
  Language: [
    { name: "@type", required: true, description: "Tipo", example: "Language" },
    { name: "name", required: true, description: "Nome do idioma", example: "Português Brasileiro" },
    { name: "alternateName", required: false, description: "Código", example: "pt-BR" },
  ],

  // ── Other important types ──
  Question: [
    { name: "@type", required: true, description: "Tipo", example: "Question" },
    { name: "name", required: true, description: "Texto da pergunta", example: "Como funciona o SEO?" },
    { name: "acceptedAnswer", required: false, description: "Resposta aceita", example: "SEO é o processo de..." },
  ],
  SearchAction: [
    { name: "@type", required: true, description: "Tipo", example: "SearchAction" },
    { name: "target", required: true, description: "URL template de busca", example: "https://example.com/busca?q={search_term}" },
    { name: "query-input", required: false, description: "Parâmetro de busca", example: "required name=search_term" },
  ],
  OpeningHoursSpecification: [
    { name: "@type", required: true, description: "Tipo", example: "OpeningHoursSpecification" },
    { name: "dayOfWeek", required: true, description: "Dia(s) da semana", example: "Monday, Tuesday, Wednesday" },
    { name: "opens", required: true, description: "Horário de abertura", example: "08:00" },
    { name: "closes", required: true, description: "Horário de fechamento", example: "18:00" },
  ],
  GeoCoordinates: [
    { name: "@type", required: true, description: "Tipo", example: "GeoCoordinates" },
    { name: "latitude", required: true, description: "Latitude", example: "-23.5505" },
    { name: "longitude", required: true, description: "Longitude", example: "-46.6333" },
  ],
  Schedule: [
    { name: "@type", required: true, description: "Tipo", example: "Schedule" },
    { name: "repeatFrequency", required: false, description: "Frequência", example: "P1W (semanal)" },
    { name: "byDay", required: false, description: "Dias", example: "Monday, Wednesday, Friday" },
    { name: "startTime", required: false, description: "Hora início", example: "09:00" },
    { name: "endTime", required: false, description: "Hora fim", example: "17:00" },
  ],
  EducationalOccupationalCredential: [
    { name: "@type", required: true, description: "Tipo", example: "EducationalOccupationalCredential" },
    { name: "name", required: true, description: "Nome da credencial", example: "MBA em Marketing Digital" },
    { name: "credentialCategory", required: false, description: "Categoria", example: "Pós-Graduação" },
    { name: "recognizedBy", required: false, description: "Reconhecida por", example: "MEC" },
    { name: "educationalLevel", required: false, description: "Nível", example: "Master" },
  ],
  Certification: [
    { name: "@type", required: true, description: "Tipo", example: "Certification" },
    { name: "name", required: true, description: "Nome da certificação", example: "Google Analytics Certified" },
    { name: "certificationIdentification", required: false, description: "Nº do certificado", example: "GA-2025-001" },
    { name: "issuedBy", required: false, description: "Emitido por", example: "Google" },
    { name: "validFrom", required: false, description: "Válido desde", example: "2024-06-01" },
    { name: "expires", required: false, description: "Expira em", example: "2026-06-01" },
  ],
  WarrantyPromise: [
    { name: "@type", required: true, description: "Tipo", example: "WarrantyPromise" },
    { name: "durationOfWarranty", required: false, description: "Duração", example: "P1Y (1 ano)" },
    { name: "warrantyScope", required: false, description: "Escopo", example: "Defeitos de fabricação" },
  ],
  Menu: [
    { name: "@type", required: true, description: "Tipo", example: "Menu" },
    { name: "name", required: true, description: "Nome do cardápio", example: "Cardápio Principal" },
    { name: "hasMenuSection", required: false, description: "Seções", example: "Entradas, Pratos Principais" },
  ],
  MedicalProcedure: [
    { name: "@type", required: true, description: "Tipo", example: "MedicalProcedure" },
    { name: "name", required: true, description: "Nome do procedimento", example: "Consulta Cardiológica" },
    { name: "procedureType", required: false, description: "Tipo", example: "Diagnóstico" },
    { name: "howPerformed", required: false, description: "Como é realizado", example: "Avaliação clínica completa" },
    { name: "preparation", required: false, description: "Preparação", example: "Jejum de 12 horas" },
  ],
  TherapeuticProcedure: [
    { name: "@type", required: true, description: "Tipo", example: "TherapeuticProcedure" },
    { name: "name", required: true, description: "Nome", example: "Fisioterapia" },
    { name: "procedureType", required: false, description: "Tipo", example: "Terapêutico" },
  ],
  DiagnosticProcedure: [
    { name: "@type", required: true, description: "Tipo", example: "DiagnosticProcedure" },
    { name: "name", required: true, description: "Nome", example: "Ressonância Magnética" },
    { name: "procedureType", required: false, description: "Tipo", example: "Diagnóstico por imagem" },
  ],
  MedicalSpecialty: [
    { name: "@type", required: true, description: "Tipo", example: "MedicalSpecialty" },
    { name: "name", required: true, description: "Especialidade", example: "Cardiologia" },
    { name: "description", required: false, description: "Descrição", example: "Tratamento do coração..." },
  ],
  MedicalDevice: [
    { name: "@type", required: true, description: "Tipo", example: "MedicalDevice" },
    { name: "name", required: true, description: "Nome do equipamento", example: "Ultrassom Doppler" },
    { name: "description", required: false, description: "Descrição", example: "Equipamento para exames..." },
  ],
  PodcastEpisode: [
    { name: "@type", required: true, description: "Tipo", example: "PodcastEpisode" },
    { name: "name", required: true, description: "Título do episódio", example: "Ep. 42 - SEO em 2025" },
    { name: "datePublished", required: false, description: "Data", example: "2025-01-15" },
    { name: "duration", required: false, description: "Duração", example: "PT45M" },
    { name: "url", required: false, description: "URL do episódio", example: "https://podcast.com/ep42" },
    { name: "associatedMedia", required: false, description: "Arquivo de áudio", example: "https://podcast.com/ep42.mp3" },
  ],
  PodcastSeries: [
    { name: "@type", required: true, description: "Tipo", example: "PodcastSeries" },
    { name: "name", required: true, description: "Nome do podcast", example: "SEO Cast" },
    { name: "description", required: false, description: "Descrição", example: "Podcast sobre SEO..." },
    { name: "url", required: false, description: "URL", example: "https://podcast.com" },
    { name: "author", required: false, description: "Apresentador", example: "João Silva" },
  ],
  BreadcrumbList: [
    { name: "@type", required: true, description: "Tipo", example: "BreadcrumbList" },
    { name: "itemListElement", required: true, description: "Itens do breadcrumb", example: "Home > Blog > Artigo" },
  ],
  CreativeWork: [
    { name: "@type", required: true, description: "Tipo", example: "CreativeWork" },
    { name: "name", required: true, description: "Título", example: "Case de Sucesso" },
    { name: "author", required: false, description: "Autor", example: "Equipe Marketing" },
    { name: "datePublished", required: false, description: "Data", example: "2024-11-01" },
    { name: "description", required: false, description: "Descrição", example: "Como aumentamos o tráfego..." },
  ],
  Report: [
    { name: "@type", required: true, description: "Tipo", example: "Report" },
    { name: "name", required: true, description: "Título do relatório", example: "Relatório Anual 2024" },
    { name: "author", required: false, description: "Autor", example: "Equipe Analítica" },
    { name: "datePublished", required: false, description: "Data", example: "2025-01-01" },
  ],
  DigitalDocument: [
    { name: "@type", required: true, description: "Tipo", example: "DigitalDocument" },
    { name: "name", required: true, description: "Título do documento", example: "Política de Privacidade" },
    { name: "url", required: false, description: "URL", example: "https://example.com/privacidade" },
  ],
  WebAPI: [
    { name: "@type", required: true, description: "Tipo", example: "WebAPI" },
    { name: "name", required: true, description: "Nome da API", example: "API de Produtos" },
    { name: "url", required: false, description: "URL", example: "https://api.example.com" },
    { name: "documentation", required: false, description: "Documentação", example: "https://api.example.com/docs" },
  ],
  APIReference: [
    { name: "@type", required: true, description: "Tipo", example: "APIReference" },
    { name: "name", required: true, description: "Nome", example: "Referência da API" },
    { name: "programmingModel", required: false, description: "Modelo", example: "REST" },
  ],
  DeliveryEvent: [
    { name: "@type", required: true, description: "Tipo", example: "DeliveryEvent" },
    { name: "expectedArrivalFrom", required: false, description: "Chegada a partir de", example: "2025-02-01" },
    { name: "expectedArrivalUntil", required: false, description: "Chegada até", example: "2025-02-05" },
  ],
  ParcelDelivery: [
    { name: "@type", required: true, description: "Tipo", example: "ParcelDelivery" },
    { name: "trackingNumber", required: false, description: "Código de rastreio", example: "BR123456789" },
    { name: "deliveryStatus", required: false, description: "Status", example: "InTransit" },
    { name: "expectedArrivalFrom", required: false, description: "Previsão", example: "2025-02-05" },
  ],
  Thing: [
    { name: "@type", required: true, description: "Tipo genérico Schema.org", example: "Thing" },
    { name: "name", required: true, description: "Nome", example: "Categoria X" },
    { name: "description", required: false, description: "Descrição", example: "Descrição da categoria..." },
    { name: "url", required: false, description: "URL", example: "https://example.com/categoria" },
    { name: "image", required: false, description: "Imagem", example: "https://example.com/img.jpg" },
  ],
  CategoryCode: [
    { name: "@type", required: true, description: "Tipo", example: "CategoryCode" },
    { name: "name", required: true, description: "Nome da categoria", example: "Eletrônicos" },
    { name: "codeValue", required: false, description: "Código", example: "ELET-001" },
    { name: "inCodeSet", required: false, description: "Sistema de classificação", example: "Catálogo interno" },
  ],
  Taxon: [
    { name: "@type", required: true, description: "Tipo", example: "Taxon" },
    { name: "name", required: true, description: "Nome do táxon", example: "Nicho de Saúde" },
    { name: "parentTaxon", required: false, description: "Táxon pai", example: "Serviços" },
  ],
  Photograph: [
    { name: "@type", required: true, description: "Tipo", example: "Photograph" },
    { name: "name", required: true, description: "Título", example: "Foto da equipe" },
    { name: "contentUrl", required: false, description: "URL", example: "https://example.com/team.jpg" },
  ],
  Specialty: [
    { name: "@type", required: true, description: "Tipo", example: "Specialty" },
    { name: "name", required: true, description: "Nome da especialidade", example: "Ortodontia" },
    { name: "description", required: false, description: "Descrição", example: "Correção da posição dos dentes" },
  ],
  EducationalOrganization: [
    { name: "@type", required: true, description: "Tipo", example: "EducationalOrganization" },
    { name: "name", required: true, description: "Nome da instituição", example: "Escola ABC" },
    { name: "address", required: true, description: "Endereço", example: "Rua da Educação, 300" },
    { name: "telephone", required: false, description: "Telefone", example: "+55 11 9999-0000" },
  ],
  EducationalOccupationalProgram: [
    { name: "@type", required: true, description: "Tipo", example: "EducationalOccupationalProgram" },
    { name: "name", required: true, description: "Nome do programa", example: "Programa de Trainee" },
    { name: "provider", required: false, description: "Instituição", example: "Empresa XYZ" },
    { name: "timeToComplete", required: false, description: "Duração", example: "P6M (6 meses)" },
  ],
  TravelAgency: [
    { name: "@type", required: true, description: "Tipo", example: "TravelAgency" },
    { name: "name", required: true, description: "Nome da agência", example: "Viagens & Cia" },
    { name: "address", required: true, description: "Endereço", example: "Rua dos Viajantes, 100" },
    { name: "telephone", required: false, description: "Telefone", example: "+55 11 1234-5678" },
  ],
  TouristAttraction: [
    { name: "@type", required: true, description: "Tipo", example: "TouristAttraction" },
    { name: "name", required: true, description: "Nome do ponto turístico", example: "Cristo Redentor" },
    { name: "address", required: false, description: "Endereço", example: "Parque Nacional da Tijuca" },
    { name: "geo", required: false, description: "Coordenadas", example: "-22.9519, -43.2105" },
  ],
  GovernmentOrganization: [
    { name: "@type", required: true, description: "Tipo", example: "GovernmentOrganization" },
    { name: "name", required: true, description: "Nome do órgão", example: "Prefeitura Municipal" },
    { name: "url", required: false, description: "URL", example: "https://prefeitura.gov.br" },
  ],
  Consortium: [
    { name: "@type", required: true, description: "Tipo", example: "Consortium" },
    { name: "name", required: true, description: "Nome do consórcio", example: "Consórcio Tech Brasil" },
    { name: "member", required: false, description: "Membros", example: "Empresa A, Empresa B" },
  ],
  CourseInstance: [
    { name: "@type", required: true, description: "Tipo", example: "CourseInstance" },
    { name: "name", required: true, description: "Nome da turma", example: "Turma 2025.1" },
    { name: "startDate", required: false, description: "Início", example: "2025-03-01" },
    { name: "endDate", required: false, description: "Término", example: "2025-06-30" },
    { name: "courseMode", required: false, description: "Modalidade", example: "Online" },
  ],
  Clip: [
    { name: "@type", required: true, description: "Tipo", example: "Clip" },
    { name: "name", required: true, description: "Título do clipe", example: "Highlights do Evento" },
    { name: "startOffset", required: false, description: "Início no vídeo", example: "120" },
    { name: "endOffset", required: false, description: "Fim no vídeo", example: "300" },
  ],
  Movie: [
    { name: "@type", required: true, description: "Tipo", example: "Movie" },
    { name: "name", required: true, description: "Título do filme", example: "Documentário SEO" },
    { name: "director", required: false, description: "Diretor", example: "Carlos Lima" },
    { name: "duration", required: false, description: "Duração", example: "PT1H30M" },
  ],
  RadioEpisode: [
    { name: "@type", required: true, description: "Tipo", example: "RadioEpisode" },
    { name: "name", required: true, description: "Título do episódio", example: "Entrevista Especial" },
    { name: "datePublished", required: false, description: "Data", example: "2025-01-20" },
  ],
  Book: [
    { name: "@type", required: true, description: "Tipo", example: "Book" },
    { name: "name", required: true, description: "Título do livro", example: "SEO na Prática" },
    { name: "author", required: false, description: "Autor", example: "João Silva" },
    { name: "isbn", required: false, description: "ISBN", example: "978-85-12345-67-8" },
    { name: "numberOfPages", required: false, description: "Nº de páginas", example: "320" },
  ],
  Barcode: [
    { name: "@type", required: true, description: "Tipo", example: "Barcode" },
    { name: "name", required: true, description: "Nome", example: "Código de Barras" },
  ],
  Patient: [
    { name: "@type", required: true, description: "Tipo", example: "Patient" },
    { name: "name", required: true, description: "Nome do paciente", example: "João Silva" },
    { name: "healthCondition", required: false, description: "Condição", example: "Hipertensão" },
  ],
  GovernmentService: [
    { name: "@type", required: true, description: "Tipo", example: "GovernmentService" },
    { name: "name", required: true, description: "Nome do serviço", example: "Emissão de RG" },
    { name: "serviceOperator", required: false, description: "Órgão responsável", example: "SSP" },
  ],
  BroadcastService: [
    { name: "@type", required: true, description: "Tipo", example: "BroadcastService" },
    { name: "name", required: true, description: "Nome", example: "Rádio FM 90.5" },
    { name: "broadcastDisplayName", required: false, description: "Nome de exibição", example: "FM 90.5" },
  ],
  AdministrativeArea: [
    { name: "@type", required: true, description: "Tipo", example: "AdministrativeArea" },
    { name: "name", required: true, description: "Nome da área", example: "Zona Sul" },
  ],
  Country: [
    { name: "@type", required: true, description: "Tipo", example: "Country" },
    { name: "name", required: true, description: "Nome do país", example: "Brasil" },
  ],
  State: [
    { name: "@type", required: true, description: "Tipo", example: "State" },
    { name: "name", required: true, description: "Nome do estado", example: "São Paulo" },
    { name: "containedInPlace", required: false, description: "País", example: "Brasil" },
  ],
  GeoCircle: [
    { name: "@type", required: true, description: "Tipo", example: "GeoCircle" },
    { name: "geoMidpoint", required: false, description: "Ponto central", example: "-23.55, -46.63" },
    { name: "geoRadius", required: false, description: "Raio", example: "10 km" },
  ],
  GeoShape: [
    { name: "@type", required: true, description: "Tipo", example: "GeoShape" },
    { name: "polygon", required: false, description: "Polígono", example: "-23.5,-46.6 -23.6,-46.7..." },
  ],
  EndorsementRating: [
    { name: "@type", required: true, description: "Tipo", example: "EndorsementRating" },
    { name: "ratingValue", required: true, description: "Nota de endosso", example: "5" },
  ],
  CriticReview: [
    { name: "@type", required: true, description: "Tipo", example: "CriticReview" },
    { name: "reviewBody", required: true, description: "Texto da crítica", example: "Excelente abordagem..." },
    { name: "author", required: true, description: "Crítico", example: "Pedro Crítico" },
  ],
  Testimonial: [
    { name: "@type", required: true, description: "Tipo (não oficial Schema.org, use Review)", example: "Review" },
    { name: "reviewBody", required: true, description: "Texto do depoimento", example: "Mudou meu negócio!" },
    { name: "author", required: true, description: "Autor", example: "Cliente Satisfeito" },
  ],
};

/**
 * Get Schema.org properties for a given schema type.
 * Falls back to Organization if not found.
 */
export function getSchemaProperties(schemaType: string): SchemaProperty[] {
  return SCHEMA_PROPERTIES[schemaType] || SCHEMA_PROPERTIES["Thing"] || [];
}
