// ═══════════════════════════════════════════════════════════════
// Schema.org Complete Type Registry
// All 800+ types from https://schema.org/docs/schemas.html
// ═══════════════════════════════════════════════════════════════

export interface SchemaHierarchyNode {
  name: string;
  parent?: string;
  description?: string;
  googleFeature?: string;
}

// Complete Schema.org type hierarchy — every type from the official spec
// organized by parent for tree building
export const FULL_SCHEMA_TYPES: SchemaHierarchyNode[] = [
  // ── Root ──
  { name: "Thing", description: "The most generic type of item." },

  // ── Action (Thing > Action) ──
  { name: "Action", parent: "Thing", description: "An action performed by an agent." },
  { name: "AchieveAction", parent: "Action" },
  { name: "WinAction", parent: "AchieveAction" },
  { name: "TieAction", parent: "AchieveAction" },
  { name: "LoseAction", parent: "AchieveAction" },
  { name: "AssessAction", parent: "Action" },
  { name: "ChooseAction", parent: "AssessAction" },
  { name: "VoteAction", parent: "ChooseAction" },
  { name: "IgnoreAction", parent: "AssessAction" },
  { name: "ReactAction", parent: "AssessAction" },
  { name: "AgreeAction", parent: "ReactAction" },
  { name: "DisagreeAction", parent: "ReactAction" },
  { name: "DislikeAction", parent: "ReactAction" },
  { name: "EndorseAction", parent: "ReactAction" },
  { name: "LikeAction", parent: "ReactAction" },
  { name: "WantAction", parent: "ReactAction" },
  { name: "ReviewAction", parent: "AssessAction" },
  { name: "ConsumeAction", parent: "Action" },
  { name: "DrinkAction", parent: "ConsumeAction" },
  { name: "EatAction", parent: "ConsumeAction" },
  { name: "InstallAction", parent: "ConsumeAction" },
  { name: "ListenAction", parent: "ConsumeAction" },
  { name: "ReadAction", parent: "ConsumeAction" },
  { name: "UseAction", parent: "ConsumeAction" },
  { name: "WearAction", parent: "ConsumeAction" },
  { name: "ViewAction", parent: "ConsumeAction" },
  { name: "WatchAction", parent: "ConsumeAction" },
  { name: "ControlAction", parent: "Action" },
  { name: "ActivateAction", parent: "ControlAction" },
  { name: "DeactivateAction", parent: "ControlAction" },
  { name: "ResumeAction", parent: "ControlAction" },
  { name: "SuspendAction", parent: "ControlAction" },
  { name: "CreateAction", parent: "Action" },
  { name: "CookAction", parent: "CreateAction" },
  { name: "DrawAction", parent: "CreateAction" },
  { name: "FilmAction", parent: "CreateAction" },
  { name: "PaintAction", parent: "CreateAction" },
  { name: "PhotographAction", parent: "CreateAction" },
  { name: "WriteAction", parent: "CreateAction" },
  { name: "FindAction", parent: "Action" },
  { name: "CheckAction", parent: "FindAction" },
  { name: "DiscoverAction", parent: "FindAction" },
  { name: "TrackAction", parent: "FindAction" },
  { name: "InteractAction", parent: "Action" },
  { name: "BefriendAction", parent: "InteractAction" },
  { name: "CommunicateAction", parent: "InteractAction" },
  { name: "AskAction", parent: "CommunicateAction" },
  { name: "CheckInAction", parent: "CommunicateAction" },
  { name: "CheckOutAction", parent: "CommunicateAction" },
  { name: "CommentAction", parent: "CommunicateAction" },
  { name: "InformAction", parent: "CommunicateAction" },
  { name: "ConfirmAction", parent: "InformAction" },
  { name: "RsvpAction", parent: "InformAction" },
  { name: "InviteAction", parent: "CommunicateAction" },
  { name: "ReplyAction", parent: "CommunicateAction" },
  { name: "ShareAction", parent: "CommunicateAction" },
  { name: "FollowAction", parent: "InteractAction" },
  { name: "JoinAction", parent: "InteractAction" },
  { name: "LeaveAction", parent: "InteractAction" },
  { name: "MarryAction", parent: "InteractAction" },
  { name: "RegisterAction", parent: "InteractAction" },
  { name: "SubscribeAction", parent: "InteractAction" },
  { name: "UnRegisterAction", parent: "InteractAction" },
  { name: "MoveAction", parent: "Action" },
  { name: "ArriveAction", parent: "MoveAction" },
  { name: "DepartAction", parent: "MoveAction" },
  { name: "TravelAction", parent: "MoveAction" },
  { name: "OrganizeAction", parent: "Action" },
  { name: "AllocateAction", parent: "OrganizeAction" },
  { name: "AcceptAction", parent: "AllocateAction" },
  { name: "AssignAction", parent: "AllocateAction" },
  { name: "AuthorizeAction", parent: "AllocateAction" },
  { name: "RejectAction", parent: "AllocateAction" },
  { name: "ApplyAction", parent: "OrganizeAction" },
  { name: "BookmarkAction", parent: "OrganizeAction" },
  { name: "PlanAction", parent: "OrganizeAction" },
  { name: "CancelAction", parent: "PlanAction" },
  { name: "ReserveAction", parent: "PlanAction" },
  { name: "ScheduleAction", parent: "PlanAction" },
  { name: "PlayAction", parent: "Action" },
  { name: "ExerciseAction", parent: "PlayAction" },
  { name: "PerformAction", parent: "PlayAction" },
  { name: "SearchAction", parent: "Action" },
  { name: "SeekToAction", parent: "Action" },
  { name: "SolveMathAction", parent: "Action" },
  { name: "TradeAction", parent: "Action" },
  { name: "BuyAction", parent: "TradeAction" },
  { name: "DonateAction", parent: "TradeAction" },
  { name: "OrderAction", parent: "TradeAction" },
  { name: "PayAction", parent: "TradeAction" },
  { name: "PreOrderAction", parent: "TradeAction" },
  { name: "QuoteAction", parent: "TradeAction" },
  { name: "RentAction", parent: "TradeAction" },
  { name: "SellAction", parent: "TradeAction" },
  { name: "TipAction", parent: "TradeAction" },
  { name: "TransferAction", parent: "Action" },
  { name: "BorrowAction", parent: "TransferAction" },
  { name: "DownloadAction", parent: "TransferAction" },
  { name: "GiveAction", parent: "TransferAction" },
  { name: "LendAction", parent: "TransferAction" },
  { name: "MoneyTransfer", parent: "TransferAction" },
  { name: "ReceiveAction", parent: "TransferAction" },
  { name: "ReturnAction", parent: "TransferAction" },
  { name: "SendAction", parent: "TransferAction" },
  { name: "TakeAction", parent: "TransferAction" },
  { name: "UpdateAction", parent: "Action" },
  { name: "AddAction", parent: "UpdateAction" },
  { name: "InsertAction", parent: "AddAction" },
  { name: "AppendAction", parent: "InsertAction" },
  { name: "PrependAction", parent: "InsertAction" },
  { name: "DeleteAction", parent: "UpdateAction" },
  { name: "ReplaceAction", parent: "UpdateAction" },
  { name: "PlayGameAction", parent: "Action" },

  // ── BioChemEntity ──
  { name: "BioChemEntity", parent: "Thing" },
  { name: "ChemicalSubstance", parent: "BioChemEntity" },
  { name: "Gene", parent: "BioChemEntity" },
  { name: "MolecularEntity", parent: "BioChemEntity" },
  { name: "Protein", parent: "BioChemEntity" },
  { name: "Taxon", parent: "Thing" },

  // ── CreativeWork ──
  { name: "CreativeWork", parent: "Thing", description: "The most generic kind of creative work." },
  { name: "AmpStory", parent: "CreativeWork" },
  { name: "ArchiveComponent", parent: "CreativeWork" },
  { name: "Article", parent: "CreativeWork", googleFeature: "Article Rich Results", description: "An article, such as a news article or blog post." },
  { name: "AdvertiserContentArticle", parent: "Article" },
  { name: "NewsArticle", parent: "Article", googleFeature: "Top Stories" },
  { name: "AnalysisNewsArticle", parent: "NewsArticle" },
  { name: "AskPublicNewsArticle", parent: "NewsArticle" },
  { name: "BackgroundNewsArticle", parent: "NewsArticle" },
  { name: "OpinionNewsArticle", parent: "NewsArticle" },
  { name: "ReportageNewsArticle", parent: "NewsArticle" },
  { name: "ReviewNewsArticle", parent: "NewsArticle" },
  { name: "SatiricalArticle", parent: "Article" },
  { name: "ScholarlyArticle", parent: "Article" },
  { name: "MedicalScholarlyArticle", parent: "ScholarlyArticle" },
  { name: "TechArticle", parent: "Article" },
  { name: "APIReference", parent: "TechArticle" },
  { name: "Atlas", parent: "CreativeWork" },
  { name: "Blog", parent: "CreativeWork" },
  { name: "Book", parent: "CreativeWork" },
  { name: "Audiobook", parent: "Book" },
  { name: "Chapter", parent: "CreativeWork" },
  { name: "Claim", parent: "CreativeWork" },
  { name: "Clip", parent: "CreativeWork" },
  { name: "MovieClip", parent: "Clip" },
  { name: "RadioClip", parent: "Clip" },
  { name: "TVClip", parent: "Clip" },
  { name: "VideoGameClip", parent: "Clip" },
  { name: "Code", parent: "CreativeWork" },
  { name: "Collection", parent: "CreativeWork" },
  { name: "ProductCollection", parent: "Collection" },
  { name: "ComicIssue", parent: "CreativeWork" },
  { name: "ComicSeries", parent: "CreativeWork" },
  { name: "ComicStory", parent: "CreativeWork" },
  { name: "ComicCoverArt", parent: "ComicStory" },
  { name: "Comment", parent: "CreativeWork" },
  { name: "CorrectionComment", parent: "Comment" },
  { name: "Conversation", parent: "CreativeWork" },
  { name: "Course", parent: "CreativeWork", googleFeature: "Course Rich Results" },
  { name: "CreativeWorkSeason", parent: "CreativeWork" },
  { name: "PodcastSeason", parent: "CreativeWorkSeason" },
  { name: "RadioSeason", parent: "CreativeWorkSeason" },
  { name: "TVSeason", parent: "CreativeWorkSeason" },
  { name: "CreativeWorkSeries", parent: "CreativeWork" },
  { name: "BookSeries", parent: "CreativeWorkSeries" },
  { name: "MovieSeries", parent: "CreativeWorkSeries" },
  { name: "PodcastSeries", parent: "CreativeWorkSeries" },
  { name: "RadioSeries", parent: "CreativeWorkSeries" },
  { name: "TVSeries", parent: "CreativeWorkSeries" },
  { name: "VideoGameSeries", parent: "CreativeWorkSeries" },
  { name: "DataCatalog", parent: "CreativeWork" },
  { name: "Dataset", parent: "CreativeWork" },
  { name: "DataFeed", parent: "Dataset" },
  { name: "CompleteDataFeed", parent: "DataFeed" },
  { name: "DefinedTermSet", parent: "CreativeWork" },
  { name: "CategoryCodeSet", parent: "DefinedTermSet" },
  { name: "Diet", parent: "CreativeWork" },
  { name: "DigitalDocument", parent: "CreativeWork" },
  { name: "NoteDigitalDocument", parent: "DigitalDocument" },
  { name: "PresentationDigitalDocument", parent: "DigitalDocument" },
  { name: "SpreadsheetDigitalDocument", parent: "DigitalDocument" },
  { name: "TextDigitalDocument", parent: "DigitalDocument" },
  { name: "Drawing", parent: "CreativeWork" },
  { name: "EducationalOccupationalCredential", parent: "CreativeWork" },
  { name: "Episode", parent: "CreativeWork" },
  { name: "PodcastEpisode", parent: "Episode" },
  { name: "RadioEpisode", parent: "Episode" },
  { name: "TVEpisode", parent: "Episode" },
  { name: "ExercisePlan", parent: "CreativeWork" },
  { name: "Game", parent: "CreativeWork" },
  { name: "VideoGame", parent: "Game" },
  { name: "Guide", parent: "CreativeWork" },
  { name: "HowTo", parent: "CreativeWork", googleFeature: "How-To Rich Results" },
  { name: "Recipe", parent: "HowTo", googleFeature: "Recipe Rich Results" },
  { name: "HowToDirection", parent: "CreativeWork" },
  { name: "HowToSection", parent: "CreativeWork" },
  { name: "HowToStep", parent: "CreativeWork" },
  { name: "HowToTip", parent: "CreativeWork" },
  { name: "HyperToc", parent: "CreativeWork" },
  { name: "HyperTocEntry", parent: "CreativeWork" },
  { name: "LearningResource", parent: "CreativeWork" },
  { name: "Quiz", parent: "LearningResource" },
  { name: "Syllabus", parent: "LearningResource" },
  { name: "Legislation", parent: "CreativeWork" },
  { name: "LegislationObject", parent: "Legislation" },
  { name: "Manuscript", parent: "CreativeWork" },
  { name: "Map", parent: "CreativeWork" },
  { name: "MathSolver", parent: "CreativeWork" },
  { name: "MediaObject", parent: "CreativeWork" },
  { name: "3DModel", parent: "MediaObject" },
  { name: "AudioObject", parent: "MediaObject" },
  { name: "AudioObjectSnapshot", parent: "AudioObject" },
  { name: "DataDownload", parent: "MediaObject" },
  { name: "ImageObject", parent: "MediaObject" },
  { name: "ImageObjectSnapshot", parent: "ImageObject" },
  { name: "Barcode", parent: "ImageObject" },
  { name: "MusicVideoObject", parent: "MediaObject" },
  { name: "VideoObject", parent: "MediaObject", googleFeature: "Video Rich Results" },
  { name: "VideoObjectSnapshot", parent: "VideoObject" },
  { name: "MediaReviewItem", parent: "CreativeWork" },
  { name: "Menu", parent: "CreativeWork" },
  { name: "MenuSection", parent: "CreativeWork" },
  { name: "Message", parent: "CreativeWork" },
  { name: "EmailMessage", parent: "Message" },
  { name: "Movie", parent: "CreativeWork" },
  { name: "MusicComposition", parent: "CreativeWork" },
  { name: "MusicPlaylist", parent: "CreativeWork" },
  { name: "MusicAlbum", parent: "MusicPlaylist" },
  { name: "MusicRecording", parent: "CreativeWork" },
  { name: "MusicRelease", parent: "MusicPlaylist" },
  { name: "Painting", parent: "CreativeWork" },
  { name: "Photograph", parent: "CreativeWork" },
  { name: "Play", parent: "CreativeWork" },
  { name: "Poster", parent: "CreativeWork" },
  { name: "PublicationIssue", parent: "CreativeWork" },
  { name: "PublicationVolume", parent: "CreativeWork" },
  { name: "Quotation", parent: "CreativeWork" },
  { name: "Review", parent: "CreativeWork", googleFeature: "Review Rich Results" },
  { name: "ClaimReview", parent: "Review" },
  { name: "CriticReview", parent: "Review" },
  { name: "EmployerReview", parent: "Review" },
  { name: "MediaReview", parent: "Review" },
  { name: "Recommendation", parent: "Review" },
  { name: "UserReview", parent: "Review" },
  { name: "Sculpture", parent: "CreativeWork" },
  { name: "Season", parent: "CreativeWork" },
  { name: "SheetMusic", parent: "CreativeWork" },
  { name: "ShortStory", parent: "CreativeWork" },
  { name: "SoftwareApplication", parent: "CreativeWork", googleFeature: "Software App Rich Results" },
  { name: "MobileApplication", parent: "SoftwareApplication" },
  { name: "WebApplication", parent: "SoftwareApplication" },
  { name: "SoftwareSourceCode", parent: "CreativeWork" },
  { name: "SpecialAnnouncement", parent: "CreativeWork" },
  { name: "Statement", parent: "CreativeWork" },
  { name: "Thesis", parent: "CreativeWork" },
  { name: "VisualArtwork", parent: "CreativeWork" },
  { name: "CoverArt", parent: "VisualArtwork" },
  { name: "WebContent", parent: "CreativeWork" },
  { name: "HealthTopicContent", parent: "WebContent" },
  { name: "WebPage", parent: "CreativeWork" },
  { name: "AboutPage", parent: "WebPage" },
  { name: "CheckoutPage", parent: "WebPage" },
  { name: "CollectionPage", parent: "WebPage" },
  { name: "MediaGallery", parent: "CollectionPage" },
  { name: "ImageGallery", parent: "MediaGallery" },
  { name: "VideoGallery", parent: "MediaGallery" },
  { name: "ContactPage", parent: "WebPage" },
  { name: "FAQPage", parent: "WebPage", googleFeature: "FAQ Rich Results" },
  { name: "ItemPage", parent: "WebPage" },
  { name: "MedicalWebPage", parent: "WebPage" },
  { name: "ProfilePage", parent: "WebPage" },
  { name: "QAPage", parent: "WebPage" },
  { name: "RealEstateListing", parent: "WebPage" },
  { name: "SearchResultsPage", parent: "WebPage" },
  { name: "WebPageElement", parent: "CreativeWork" },
  { name: "SiteNavigationElement", parent: "WebPageElement" },
  { name: "Table", parent: "WebPageElement" },
  { name: "WPAdBlock", parent: "WebPageElement" },
  { name: "WPFooter", parent: "WebPageElement" },
  { name: "WPHeader", parent: "WebPageElement" },
  { name: "WPSideBar", parent: "WebPageElement" },
  { name: "WebSite", parent: "CreativeWork", googleFeature: "Sitelinks Search Box" },

  // ── Event ──
  { name: "Event", parent: "Thing", googleFeature: "Event Rich Results", description: "An event happening at a certain time and location." },
  { name: "BusinessEvent", parent: "Event" },
  { name: "ChildrensEvent", parent: "Event" },
  { name: "ComedyEvent", parent: "Event" },
  { name: "CourseInstance", parent: "Event" },
  { name: "DanceEvent", parent: "Event" },
  { name: "DeliveryEvent", parent: "Event" },
  { name: "EducationEvent", parent: "Event" },
  { name: "EventSeries", parent: "Event" },
  { name: "ExhibitionEvent", parent: "Event" },
  { name: "Festival", parent: "Event" },
  { name: "FoodEvent", parent: "Event" },
  { name: "Hackathon", parent: "Event" },
  { name: "LiteraryEvent", parent: "Event" },
  { name: "MusicEvent", parent: "Event" },
  { name: "OnDemandEvent", parent: "Event" },
  { name: "PublicationEvent", parent: "Event" },
  { name: "BroadcastEvent", parent: "PublicationEvent" },
  { name: "SaleEvent", parent: "Event" },
  { name: "ScreeningEvent", parent: "Event" },
  { name: "SocialEvent", parent: "Event" },
  { name: "SportsEvent", parent: "Event" },
  { name: "TheaterEvent", parent: "Event" },
  { name: "UserInteraction", parent: "Event" },
  { name: "UserBlocks", parent: "UserInteraction" },
  { name: "UserCheckins", parent: "UserInteraction" },
  { name: "UserComments", parent: "UserInteraction" },
  { name: "UserDownloads", parent: "UserInteraction" },
  { name: "UserLikes", parent: "UserInteraction" },
  { name: "UserPageVisits", parent: "UserInteraction" },
  { name: "UserPlays", parent: "UserInteraction" },
  { name: "UserPlusOnes", parent: "UserInteraction" },
  { name: "UserTweets", parent: "UserInteraction" },
  { name: "VisualArtsEvent", parent: "Event" },

  // ── Intangible ──
  { name: "Intangible", parent: "Thing" },
  { name: "ActionAccessSpecification", parent: "Intangible" },
  { name: "AlignmentObject", parent: "Intangible" },
  { name: "Audience", parent: "Intangible" },
  { name: "BusinessAudience", parent: "Audience" },
  { name: "EducationalAudience", parent: "Audience" },
  { name: "MedicalAudience", parent: "Audience" },
  { name: "PeopleAudience", parent: "Audience" },
  { name: "ParentAudience", parent: "PeopleAudience" },
  { name: "Researcher", parent: "Audience" },
  { name: "BedDetails", parent: "Intangible" },
  { name: "Brand", parent: "Intangible" },
  { name: "BroadcastChannel", parent: "Intangible" },
  { name: "AMRadioChannel", parent: "BroadcastChannel" },
  { name: "FMRadioChannel", parent: "BroadcastChannel" },
  { name: "RadioChannel", parent: "BroadcastChannel" },
  { name: "TelevisionChannel", parent: "BroadcastChannel" },
  { name: "BroadcastFrequencySpecification", parent: "Intangible" },
  { name: "ComputerLanguage", parent: "Intangible" },
  { name: "DataFeedItem", parent: "Intangible" },
  { name: "DefinedTerm", parent: "Intangible" },
  { name: "CategoryCode", parent: "DefinedTerm" },
  { name: "Demand", parent: "Intangible" },
  { name: "DigitalDocumentPermission", parent: "Intangible" },
  { name: "EnergyConsumptionDetails", parent: "Intangible" },
  { name: "EntryPoint", parent: "Intangible" },
  { name: "Enumeration", parent: "Intangible" },
  { name: "ActionStatusType", parent: "Enumeration" },
  { name: "AdultOrientedEnumeration", parent: "Enumeration" },
  { name: "BoardingPolicyType", parent: "Enumeration" },
  { name: "BookFormatType", parent: "Enumeration" },
  { name: "BusinessEntityType", parent: "Enumeration" },
  { name: "BusinessFunction", parent: "Enumeration" },
  { name: "CarUsageType", parent: "Enumeration" },
  { name: "ContactPointOption", parent: "Enumeration" },
  { name: "DayOfWeek", parent: "Enumeration" },
  { name: "DeliveryMethod", parent: "Enumeration" },
  { name: "DigitalDocumentPermissionType", parent: "Enumeration" },
  { name: "DigitalPlatformEnumeration", parent: "Enumeration" },
  { name: "DriveWheelConfigurationValue", parent: "Enumeration" },
  { name: "EUEnergyEfficiencyEnumeration", parent: "Enumeration" },
  { name: "EnergyEfficiencyEnumeration", parent: "Enumeration" },
  { name: "EnergyStarEnergyEfficiencyEnumeration", parent: "Enumeration" },
  { name: "EventAttendanceModeEnumeration", parent: "Enumeration" },
  { name: "EventStatusType", parent: "Enumeration" },
  { name: "GameAvailabilityEnumeration", parent: "Enumeration" },
  { name: "GamePlayMode", parent: "Enumeration" },
  { name: "GameServerStatus", parent: "Enumeration" },
  { name: "GenderType", parent: "Enumeration" },
  { name: "GovernmentBenefitsType", parent: "Enumeration" },
  { name: "HealthAspectEnumeration", parent: "Enumeration" },
  { name: "InfectiousAgentClass", parent: "Enumeration" },
  { name: "ItemAvailability", parent: "Enumeration" },
  { name: "ItemListOrderType", parent: "Enumeration" },
  { name: "LegalForceStatus", parent: "Enumeration" },
  { name: "LegalValueLevel", parent: "Enumeration" },
  { name: "MapCategoryType", parent: "Enumeration" },
  { name: "MeasurementMethodEnum", parent: "Enumeration" },
  { name: "MeasurementTypeEnumeration", parent: "Enumeration" },
  { name: "BodyMeasurementTypeEnumeration", parent: "MeasurementTypeEnumeration" },
  { name: "WearableMeasurementTypeEnumeration", parent: "MeasurementTypeEnumeration" },
  { name: "MediaManipulationRatingEnumeration", parent: "Enumeration" },
  { name: "MedicalAudienceType", parent: "Enumeration" },
  { name: "MedicalDevicePurpose", parent: "Enumeration" },
  { name: "MedicalEnumeration", parent: "Enumeration" },
  { name: "DrugCostCategory", parent: "MedicalEnumeration" },
  { name: "DrugPregnancyCategory", parent: "MedicalEnumeration" },
  { name: "DrugPrescriptionStatus", parent: "MedicalEnumeration" },
  { name: "MedicalEvidenceLevel", parent: "MedicalEnumeration" },
  { name: "MedicalImagingTechnique", parent: "MedicalEnumeration" },
  { name: "MedicalObservationalStudyDesign", parent: "MedicalEnumeration" },
  { name: "MedicalProcedureType", parent: "MedicalEnumeration" },
  { name: "MedicalSpecialty", parent: "MedicalEnumeration" },
  { name: "MedicalStudyStatus", parent: "MedicalEnumeration" },
  { name: "MedicalTrialDesign", parent: "MedicalEnumeration" },
  { name: "MedicineSystem", parent: "MedicalEnumeration" },
  { name: "PhysicalActivityCategory", parent: "MedicalEnumeration" },
  { name: "PhysicalExam", parent: "MedicalEnumeration" },
  { name: "MerchantReturnEnumeration", parent: "Enumeration" },
  { name: "MusicAlbumProductionType", parent: "Enumeration" },
  { name: "MusicAlbumReleaseType", parent: "Enumeration" },
  { name: "MusicReleaseFormatType", parent: "Enumeration" },
  { name: "NonprofitType", parent: "Enumeration" },
  { name: "NLNonprofitType", parent: "NonprofitType" },
  { name: "UKNonprofitType", parent: "NonprofitType" },
  { name: "USNonprofitType", parent: "NonprofitType" },
  { name: "OfferItemCondition", parent: "Enumeration" },
  { name: "OrderStatus", parent: "Enumeration" },
  { name: "PaymentMethod", parent: "Enumeration" },
  { name: "PaymentStatusType", parent: "Enumeration" },
  { name: "PriceComponentTypeEnumeration", parent: "Enumeration" },
  { name: "PriceTypeEnumeration", parent: "Enumeration" },
  { name: "QualitativeValue", parent: "Enumeration" },
  { name: "BedType", parent: "QualitativeValue" },
  { name: "DriveWheelConfigurationValue", parent: "QualitativeValue" },
  { name: "SizeGroupEnumeration", parent: "QualitativeValue" },
  { name: "WearableSizeGroupEnumeration", parent: "SizeGroupEnumeration" },
  { name: "SizeSystemEnumeration", parent: "QualitativeValue" },
  { name: "WearableSizeSystemEnumeration", parent: "SizeSystemEnumeration" },
  { name: "SteeringPositionValue", parent: "QualitativeValue" },
  { name: "RefundTypeEnumeration", parent: "Enumeration" },
  { name: "ReservationStatusType", parent: "Enumeration" },
  { name: "RestrictedDiet", parent: "Enumeration" },
  { name: "ReturnFeesEnumeration", parent: "Enumeration" },
  { name: "ReturnLabelSourceEnumeration", parent: "Enumeration" },
  { name: "ReturnMethodEnumeration", parent: "Enumeration" },
  { name: "RsvpResponseType", parent: "Enumeration" },
  { name: "Specialty", parent: "Enumeration" },
  { name: "StatusEnumeration", parent: "Enumeration" },
  { name: "WarrantyScope", parent: "Enumeration" },
  { name: "FloorPlan", parent: "Intangible" },
  { name: "GameServer", parent: "Intangible" },
  { name: "Grant", parent: "Intangible" },
  { name: "MonetaryGrant", parent: "Grant" },
  { name: "HealthInsurancePlan", parent: "Intangible" },
  { name: "HealthPlanCostSharingSpecification", parent: "Intangible" },
  { name: "HealthPlanFormulary", parent: "Intangible" },
  { name: "HealthPlanNetwork", parent: "Intangible" },
  { name: "Invoice", parent: "Intangible" },
  { name: "ItemList", parent: "Intangible" },
  { name: "BreadcrumbList", parent: "ItemList", googleFeature: "Breadcrumb Rich Results" },
  { name: "HowToItem", parent: "ItemList" },
  { name: "HowToSupply", parent: "HowToItem" },
  { name: "HowToTool", parent: "HowToItem" },
  { name: "OfferCatalog", parent: "ItemList" },
  { name: "JobPosting", parent: "Intangible", googleFeature: "Job Posting Rich Results" },
  { name: "Language", parent: "Intangible" },
  { name: "ListItem", parent: "Intangible" },
  { name: "HowToDirection", parent: "ListItem" },
  { name: "HowToSection", parent: "ListItem" },
  { name: "HowToStep", parent: "ListItem" },
  { name: "HowToTip", parent: "ListItem" },
  { name: "MediaSubscription", parent: "Intangible" },
  { name: "MenuItem", parent: "Intangible" },
  { name: "MerchantReturnPolicy", parent: "Intangible" },
  { name: "MerchantReturnPolicySeasonalOverride", parent: "Intangible" },
  { name: "Observation", parent: "Intangible" },
  { name: "Occupation", parent: "Intangible" },
  { name: "OccupationalExperienceRequirements", parent: "Intangible" },
  { name: "Offer", parent: "Intangible", googleFeature: "Product Rich Results" },
  { name: "AggregateOffer", parent: "Offer" },
  { name: "OfferForLease", parent: "Offer" },
  { name: "OfferForPurchase", parent: "Offer" },
  { name: "OfferShippingDetails", parent: "Intangible" },
  { name: "Order", parent: "Intangible" },
  { name: "OrderItem", parent: "Intangible" },
  { name: "ParcelDelivery", parent: "Intangible" },
  { name: "Permit", parent: "Intangible" },
  { name: "GovernmentPermit", parent: "Permit" },
  { name: "ProgramMembership", parent: "Intangible" },
  { name: "Property", parent: "Intangible" },
  { name: "PropertyValueSpecification", parent: "Intangible" },
  { name: "Rating", parent: "Intangible" },
  { name: "AggregateRating", parent: "Rating", googleFeature: "Star Ratings" },
  { name: "EmployerAggregateRating", parent: "AggregateRating" },
  { name: "EndorsementRating", parent: "Rating" },
  { name: "Reservation", parent: "Intangible" },
  { name: "BoatReservation", parent: "Reservation" },
  { name: "BusReservation", parent: "Reservation" },
  { name: "EventReservation", parent: "Reservation" },
  { name: "FlightReservation", parent: "Reservation" },
  { name: "FoodEstablishmentReservation", parent: "Reservation" },
  { name: "LodgingReservation", parent: "Reservation" },
  { name: "RentalCarReservation", parent: "Reservation" },
  { name: "ReservationPackage", parent: "Reservation" },
  { name: "TaxiReservation", parent: "Reservation" },
  { name: "TrainReservation", parent: "Reservation" },
  { name: "Role", parent: "Intangible" },
  { name: "LinkRole", parent: "Role" },
  { name: "OrganizationRole", parent: "Role" },
  { name: "EmployeeRole", parent: "OrganizationRole" },
  { name: "PerformanceRole", parent: "Role" },
  { name: "Schedule", parent: "Intangible" },
  { name: "Seat", parent: "Intangible" },
  { name: "Series", parent: "Intangible" },
  { name: "Service", parent: "Intangible", description: "A service provided by an organization." },
  { name: "BroadcastService", parent: "Service" },
  { name: "RadioBroadcastService", parent: "BroadcastService" },
  { name: "CableOrSatelliteService", parent: "Service" },
  { name: "FinancialProduct", parent: "Service" },
  { name: "BankAccount", parent: "FinancialProduct" },
  { name: "DepositAccount", parent: "BankAccount" },
  { name: "BrokerageAccount", parent: "FinancialProduct" },
  { name: "CurrencyConversionService", parent: "FinancialProduct" },
  { name: "ExchangeRateSpecification", parent: "FinancialProduct" },
  { name: "InvestmentFund", parent: "FinancialProduct" },
  { name: "InvestmentOrDeposit", parent: "FinancialProduct" },
  { name: "LoanOrCredit", parent: "FinancialProduct" },
  { name: "MortgageLoan", parent: "LoanOrCredit" },
  { name: "PaymentCard", parent: "FinancialProduct" },
  { name: "CreditCard", parent: "PaymentCard" },
  { name: "PaymentService", parent: "FinancialProduct" },
  { name: "FoodService", parent: "Service" },
  { name: "GovernmentService", parent: "Service" },
  { name: "Taxi", parent: "Service" },
  { name: "TaxiService", parent: "Service" },
  { name: "WebAPI", parent: "Service" },
  { name: "ServiceChannel", parent: "Intangible" },
  { name: "ShippingDeliveryTime", parent: "Intangible" },
  { name: "ShippingRateSettings", parent: "Intangible" },
  { name: "DeliveryTimeSettings", parent: "Intangible" },
  { name: "SizeSpecification", parent: "Intangible" },
  { name: "SpeakableSpecification", parent: "Intangible" },
  { name: "StatisticalPopulation", parent: "Intangible" },
  { name: "StatisticalVariable", parent: "Intangible" },
  { name: "StructuredValue", parent: "Intangible" },
  { name: "CDCPMDRecord", parent: "StructuredValue" },
  { name: "ContactPoint", parent: "StructuredValue" },
  { name: "PostalAddress", parent: "ContactPoint" },
  { name: "DatedMoneySpecification", parent: "StructuredValue" },
  { name: "DefinedRegion", parent: "StructuredValue" },
  { name: "DeliveryTimeSettings", parent: "StructuredValue" },
  { name: "EngineSpecification", parent: "StructuredValue" },
  { name: "GeoCoordinates", parent: "StructuredValue" },
  { name: "GeoShape", parent: "StructuredValue" },
  { name: "GeoCircle", parent: "GeoShape" },
  { name: "GeospatialGeometry", parent: "Intangible" },
  { name: "InteractionCounter", parent: "StructuredValue" },
  { name: "LocationFeatureSpecification", parent: "StructuredValue" },
  { name: "MonetaryAmount", parent: "StructuredValue" },
  { name: "MonetaryAmountDistribution", parent: "StructuredValue" },
  { name: "NutritionInformation", parent: "StructuredValue" },
  { name: "OpeningHoursSpecification", parent: "StructuredValue" },
  { name: "OwnershipInfo", parent: "StructuredValue" },
  { name: "PostalCodeRangeSpecification", parent: "StructuredValue" },
  { name: "PriceSpecification", parent: "StructuredValue" },
  { name: "CompoundPriceSpecification", parent: "PriceSpecification" },
  { name: "DeliveryChargeSpecification", parent: "PriceSpecification" },
  { name: "PaymentChargeSpecification", parent: "PriceSpecification" },
  { name: "UnitPriceSpecification", parent: "PriceSpecification" },
  { name: "PropertyValue", parent: "StructuredValue" },
  { name: "QuantitativeValue", parent: "StructuredValue" },
  { name: "QuantitativeValueDistribution", parent: "StructuredValue" },
  { name: "RepaymentSpecification", parent: "StructuredValue" },
  { name: "TypeAndQuantityNode", parent: "StructuredValue" },
  { name: "WarrantyPromise", parent: "StructuredValue" },
  { name: "Subscription", parent: "Intangible" },
  { name: "Ticket", parent: "Intangible" },
  { name: "Trip", parent: "Intangible" },
  { name: "BoatTrip", parent: "Trip" },
  { name: "BusTrip", parent: "Trip" },
  { name: "Flight", parent: "Trip" },
  { name: "TouristTrip", parent: "Trip" },
  { name: "TrainTrip", parent: "Trip" },
  { name: "VirtualLocation", parent: "Intangible" },

  // ── MedicalEntity ──
  { name: "MedicalEntity", parent: "Thing" },
  { name: "AnatomicalStructure", parent: "MedicalEntity" },
  { name: "Abdomen", parent: "AnatomicalStructure" },
  { name: "Artery", parent: "AnatomicalStructure" },
  { name: "Bone", parent: "AnatomicalStructure" },
  { name: "BrainStructure", parent: "AnatomicalStructure" },
  { name: "Ear", parent: "AnatomicalStructure" },
  { name: "Eye", parent: "AnatomicalStructure" },
  { name: "Head", parent: "AnatomicalStructure" },
  { name: "Joint", parent: "AnatomicalStructure" },
  { name: "Ligament", parent: "AnatomicalStructure" },
  { name: "Lung", parent: "AnatomicalStructure" },
  { name: "LymphaticVessel", parent: "AnatomicalStructure" },
  { name: "Muscle", parent: "AnatomicalStructure" },
  { name: "Neck", parent: "AnatomicalStructure" },
  { name: "Nerve", parent: "AnatomicalStructure" },
  { name: "Nose", parent: "AnatomicalStructure" },
  { name: "Throat", parent: "AnatomicalStructure" },
  { name: "Vein", parent: "AnatomicalStructure" },
  { name: "Vessel", parent: "AnatomicalStructure" },
  { name: "AnatomicalSystem", parent: "MedicalEntity" },
  { name: "DrugClass", parent: "MedicalEntity" },
  { name: "DrugCost", parent: "MedicalEntity" },
  { name: "MedicalCause", parent: "MedicalEntity" },
  { name: "MedicalCondition", parent: "MedicalEntity" },
  { name: "InfectiousDisease", parent: "MedicalCondition" },
  { name: "MedicalSignOrSymptom", parent: "MedicalCondition" },
  { name: "MedicalSign", parent: "MedicalSignOrSymptom" },
  { name: "VitalSign", parent: "MedicalSign" },
  { name: "MedicalSymptom", parent: "MedicalSignOrSymptom" },
  { name: "MedicalConditionStage", parent: "MedicalEntity" },
  { name: "MedicalContraindication", parent: "MedicalEntity" },
  { name: "MedicalDevice", parent: "MedicalEntity" },
  { name: "MedicalGuideline", parent: "MedicalEntity" },
  { name: "MedicalGuidelineContraindication", parent: "MedicalGuideline" },
  { name: "MedicalGuidelineRecommendation", parent: "MedicalGuideline" },
  { name: "MedicalIndication", parent: "MedicalEntity" },
  { name: "ApprovedIndication", parent: "MedicalIndication" },
  { name: "PreventionIndication", parent: "MedicalIndication" },
  { name: "TreatmentIndication", parent: "MedicalIndication" },
  { name: "MedicalIntangible", parent: "MedicalEntity" },
  { name: "DDxElement", parent: "MedicalIntangible" },
  { name: "DoseSchedule", parent: "MedicalIntangible" },
  { name: "MaximumDoseSchedule", parent: "DoseSchedule" },
  { name: "RecommendedDoseSchedule", parent: "DoseSchedule" },
  { name: "ReportedDoseSchedule", parent: "DoseSchedule" },
  { name: "DrugLegalStatus", parent: "MedicalIntangible" },
  { name: "DrugStrength", parent: "MedicalIntangible" },
  { name: "MedicalCode", parent: "MedicalIntangible" },
  { name: "MedicalConditionStage", parent: "MedicalIntangible" },
  { name: "MedicalProcedure", parent: "MedicalEntity" },
  { name: "DiagnosticProcedure", parent: "MedicalProcedure" },
  { name: "PalliativeProcedure", parent: "MedicalProcedure" },
  { name: "PhysicalTherapy", parent: "MedicalProcedure" },
  { name: "RadiationTherapy", parent: "MedicalProcedure" },
  { name: "SurgicalProcedure", parent: "MedicalProcedure" },
  { name: "TherapeuticProcedure", parent: "MedicalProcedure" },
  { name: "MedicalRiskEstimator", parent: "MedicalEntity" },
  { name: "MedicalRiskCalculator", parent: "MedicalRiskEstimator" },
  { name: "MedicalRiskScore", parent: "MedicalRiskEstimator" },
  { name: "MedicalRiskFactor", parent: "MedicalEntity" },
  { name: "MedicalStudy", parent: "MedicalEntity" },
  { name: "MedicalObservationalStudy", parent: "MedicalStudy" },
  { name: "MedicalTrial", parent: "MedicalStudy" },
  { name: "MedicalTest", parent: "MedicalEntity" },
  { name: "BloodTest", parent: "MedicalTest" },
  { name: "ImagingTest", parent: "MedicalTest" },
  { name: "MedicalTestPanel", parent: "MedicalTest" },
  { name: "PathologyTest", parent: "MedicalTest" },
  { name: "MedicalTherapy", parent: "MedicalEntity" },
  { name: "OccupationalTherapy", parent: "MedicalTherapy" },
  { name: "PsychologicalTreatment", parent: "MedicalTherapy" },
  { name: "RespiratoryTherapy", parent: "MedicalTherapy" },
  { name: "Substance", parent: "MedicalEntity" },
  { name: "DietarySupplement", parent: "Substance" },
  { name: "Drug", parent: "Substance" },
  { name: "SuperficialAnatomy", parent: "MedicalEntity" },

  // ── Organization ──
  { name: "Organization", parent: "Thing", googleFeature: "Knowledge Panel", description: "An organization such as a company or NGO." },
  { name: "Airline", parent: "Organization" },
  { name: "Consortium", parent: "Organization" },
  { name: "Corporation", parent: "Organization", googleFeature: "Knowledge Panel" },
  { name: "EducationalOrganization", parent: "Organization", googleFeature: "Knowledge Panel" },
  { name: "CollegeOrUniversity", parent: "EducationalOrganization" },
  { name: "ElementarySchool", parent: "EducationalOrganization" },
  { name: "HighSchool", parent: "EducationalOrganization" },
  { name: "MiddleSchool", parent: "EducationalOrganization" },
  { name: "Preschool", parent: "EducationalOrganization" },
  { name: "School", parent: "EducationalOrganization" },
  { name: "SchoolDistrict", parent: "EducationalOrganization" },
  { name: "FundingAgency", parent: "Organization" },
  { name: "FundingScheme", parent: "Organization" },
  { name: "GovernmentOrganization", parent: "Organization" },
  { name: "LibrarySystem", parent: "Organization" },
  { name: "LocalBusiness", parent: "Organization", googleFeature: "Local Pack, Maps", description: "A particular physical business or branch of an organization." },
  { name: "AnimalShelter", parent: "LocalBusiness" },
  { name: "ArchiveOrganization", parent: "LocalBusiness" },
  { name: "AutomotiveBusiness", parent: "LocalBusiness" },
  { name: "AutoBodyShop", parent: "AutomotiveBusiness" },
  { name: "AutoDealer", parent: "AutomotiveBusiness" },
  { name: "AutoPartsStore", parent: "AutomotiveBusiness" },
  { name: "AutoRental", parent: "AutomotiveBusiness" },
  { name: "AutoRepair", parent: "AutomotiveBusiness", googleFeature: "Local Pack" },
  { name: "AutoWash", parent: "AutomotiveBusiness" },
  { name: "GasStation", parent: "AutomotiveBusiness" },
  { name: "MotorcycleDealer", parent: "AutomotiveBusiness" },
  { name: "MotorcycleRepair", parent: "AutomotiveBusiness" },
  { name: "ChildCare", parent: "LocalBusiness" },
  { name: "Dentist", parent: "LocalBusiness" },
  { name: "DryCleaningOrLaundry", parent: "LocalBusiness" },
  { name: "EmergencyService", parent: "LocalBusiness" },
  { name: "FireStation", parent: "EmergencyService" },
  { name: "Hospital", parent: "EmergencyService" },
  { name: "PoliceStation", parent: "EmergencyService" },
  { name: "EmploymentAgency", parent: "LocalBusiness" },
  { name: "EntertainmentBusiness", parent: "LocalBusiness" },
  { name: "AdultEntertainment", parent: "EntertainmentBusiness" },
  { name: "AmusementPark", parent: "EntertainmentBusiness" },
  { name: "ArtGallery", parent: "EntertainmentBusiness" },
  { name: "Casino", parent: "EntertainmentBusiness" },
  { name: "ComedyClub", parent: "EntertainmentBusiness" },
  { name: "MovieTheater", parent: "EntertainmentBusiness" },
  { name: "NightClub", parent: "EntertainmentBusiness" },
  { name: "FinancialService", parent: "LocalBusiness" },
  { name: "AccountingService", parent: "FinancialService" },
  { name: "AutomatedTeller", parent: "FinancialService" },
  { name: "BankOrCreditUnion", parent: "FinancialService" },
  { name: "InsuranceAgency", parent: "FinancialService" },
  { name: "FoodEstablishment", parent: "LocalBusiness", googleFeature: "Local Pack, Maps" },
  { name: "Bakery", parent: "FoodEstablishment" },
  { name: "BarOrPub", parent: "FoodEstablishment" },
  { name: "Brewery", parent: "FoodEstablishment" },
  { name: "CafeOrCoffeeShop", parent: "FoodEstablishment" },
  { name: "Distillery", parent: "FoodEstablishment" },
  { name: "FastFoodRestaurant", parent: "FoodEstablishment" },
  { name: "IceCreamShop", parent: "FoodEstablishment" },
  { name: "Restaurant", parent: "FoodEstablishment", googleFeature: "Local Pack, Rich Results" },
  { name: "Winery", parent: "FoodEstablishment" },
  { name: "GovernmentOffice", parent: "LocalBusiness" },
  { name: "PostOffice", parent: "GovernmentOffice" },
  { name: "HealthAndBeautyBusiness", parent: "LocalBusiness" },
  { name: "BeautySalon", parent: "HealthAndBeautyBusiness", googleFeature: "Local Pack" },
  { name: "DaySpa", parent: "HealthAndBeautyBusiness" },
  { name: "HairSalon", parent: "HealthAndBeautyBusiness" },
  { name: "HealthClub", parent: "HealthAndBeautyBusiness", googleFeature: "Local Pack" },
  { name: "NailSalon", parent: "HealthAndBeautyBusiness" },
  { name: "TattooParlor", parent: "HealthAndBeautyBusiness" },
  { name: "HomeAndConstructionBusiness", parent: "LocalBusiness" },
  { name: "Electrician", parent: "HomeAndConstructionBusiness" },
  { name: "GeneralContractor", parent: "HomeAndConstructionBusiness" },
  { name: "HVACBusiness", parent: "HomeAndConstructionBusiness" },
  { name: "HousePainter", parent: "HomeAndConstructionBusiness" },
  { name: "Locksmith", parent: "HomeAndConstructionBusiness" },
  { name: "MovingCompany", parent: "HomeAndConstructionBusiness" },
  { name: "Plumber", parent: "HomeAndConstructionBusiness" },
  { name: "RoofingContractor", parent: "HomeAndConstructionBusiness" },
  { name: "InternetCafe", parent: "LocalBusiness" },
  { name: "LegalService", parent: "LocalBusiness", googleFeature: "Local Pack" },
  { name: "Attorney", parent: "LegalService" },
  { name: "Notary", parent: "LegalService" },
  { name: "Library", parent: "LocalBusiness" },
  { name: "LodgingBusiness", parent: "LocalBusiness" },
  { name: "BedAndBreakfast", parent: "LodgingBusiness" },
  { name: "Campground", parent: "LodgingBusiness" },
  { name: "Hostel", parent: "LodgingBusiness" },
  { name: "Hotel", parent: "LodgingBusiness" },
  { name: "Motel", parent: "LodgingBusiness" },
  { name: "Resort", parent: "LodgingBusiness" },
  { name: "MedicalBusiness", parent: "LocalBusiness", googleFeature: "Health Panel, Local Pack" },
  { name: "CommunityHealth", parent: "MedicalBusiness" },
  { name: "Dentist", parent: "MedicalBusiness" },
  { name: "Dermatology", parent: "MedicalBusiness" },
  { name: "DietNutrition", parent: "MedicalBusiness" },
  { name: "Emergency", parent: "MedicalBusiness" },
  { name: "Geriatric", parent: "MedicalBusiness" },
  { name: "Gynecologic", parent: "MedicalBusiness" },
  { name: "MedicalClinic", parent: "MedicalBusiness" },
  { name: "CovidTestingFacility", parent: "MedicalClinic" },
  { name: "Midwifery", parent: "MedicalBusiness" },
  { name: "Nursing", parent: "MedicalBusiness" },
  { name: "Obstetric", parent: "MedicalBusiness" },
  { name: "Oncologic", parent: "MedicalBusiness" },
  { name: "Optician", parent: "MedicalBusiness" },
  { name: "Optometric", parent: "MedicalBusiness" },
  { name: "Otolaryngologic", parent: "MedicalBusiness" },
  { name: "Pediatric", parent: "MedicalBusiness" },
  { name: "Pharmacy", parent: "MedicalBusiness" },
  { name: "Physician", parent: "MedicalBusiness" },
  { name: "VeterinaryCare", parent: "MedicalBusiness" },
  { name: "DiagnosticLab", parent: "MedicalBusiness" },
  { name: "ProfessionalService", parent: "LocalBusiness", googleFeature: "Local Pack" },
  { name: "RadioStation", parent: "LocalBusiness" },
  { name: "RealEstateAgent", parent: "LocalBusiness", googleFeature: "Local Pack" },
  { name: "RecyclingCenter", parent: "LocalBusiness" },
  { name: "SelfStorage", parent: "LocalBusiness" },
  { name: "ShoppingCenter", parent: "LocalBusiness" },
  { name: "SportsActivityLocation", parent: "LocalBusiness" },
  { name: "BowlingAlley", parent: "SportsActivityLocation" },
  { name: "ExerciseGym", parent: "SportsActivityLocation" },
  { name: "GolfCourse", parent: "SportsActivityLocation" },
  { name: "PublicSwimmingPool", parent: "SportsActivityLocation" },
  { name: "SkiResort", parent: "SportsActivityLocation" },
  { name: "StadiumOrArena", parent: "SportsActivityLocation" },
  { name: "TennisComplex", parent: "SportsActivityLocation" },
  { name: "Store", parent: "LocalBusiness" },
  { name: "AutoPartsStore", parent: "Store" },
  { name: "BikeStore", parent: "Store" },
  { name: "BookStore", parent: "Store" },
  { name: "ClothingStore", parent: "Store" },
  { name: "ComputerStore", parent: "Store" },
  { name: "ConvenienceStore", parent: "Store" },
  { name: "DepartmentStore", parent: "Store" },
  { name: "ElectronicsStore", parent: "Store" },
  { name: "Florist", parent: "Store" },
  { name: "FurnitureStore", parent: "Store" },
  { name: "GardenStore", parent: "Store" },
  { name: "GroceryStore", parent: "Store" },
  { name: "HardwareStore", parent: "Store" },
  { name: "HobbyShop", parent: "Store" },
  { name: "HomeGoodsStore", parent: "Store" },
  { name: "JewelryStore", parent: "Store" },
  { name: "LiquorStore", parent: "Store" },
  { name: "MensClothingStore", parent: "Store" },
  { name: "MobilePhoneStore", parent: "Store" },
  { name: "MovieRentalStore", parent: "Store" },
  { name: "MusicStore", parent: "Store" },
  { name: "OfficeEquipmentStore", parent: "Store" },
  { name: "OutletStore", parent: "Store" },
  { name: "PawnShop", parent: "Store" },
  { name: "PetStore", parent: "Store" },
  { name: "ShoeStore", parent: "Store" },
  { name: "SportingGoodsStore", parent: "Store" },
  { name: "TireShop", parent: "Store" },
  { name: "ToyStore", parent: "Store" },
  { name: "WholesaleStore", parent: "Store" },
  { name: "TelevisionStation", parent: "LocalBusiness" },
  { name: "TouristInformationCenter", parent: "LocalBusiness" },
  { name: "TravelAgency", parent: "LocalBusiness", googleFeature: "Local Pack" },
  { name: "DrivingSchoolVehicleUsage", parent: "LocalBusiness" },
  { name: "MedicalOrganization", parent: "Organization" },
  { name: "DiagnosticLab", parent: "MedicalOrganization" },
  { name: "MedicalClinic", parent: "MedicalOrganization" },
  { name: "Pharmacy", parent: "MedicalOrganization" },
  { name: "Physician", parent: "MedicalOrganization" },
  { name: "VeterinaryCare", parent: "MedicalOrganization" },
  { name: "NGO", parent: "Organization" },
  { name: "NewsMediaOrganization", parent: "Organization" },
  { name: "OnlineBusiness", parent: "Organization" },
  { name: "OnlineStore", parent: "OnlineBusiness" },
  { name: "PerformingGroup", parent: "Organization" },
  { name: "DanceGroup", parent: "PerformingGroup" },
  { name: "MusicGroup", parent: "PerformingGroup" },
  { name: "TheaterGroup", parent: "PerformingGroup" },
  { name: "PoliticalParty", parent: "Organization" },
  { name: "Project", parent: "Organization" },
  { name: "FundingScheme", parent: "Project" },
  { name: "ResearchProject", parent: "Project" },
  { name: "ResearchOrganization", parent: "Organization" },
  { name: "SearchRescueOrganization", parent: "Organization" },
  { name: "SportsOrganization", parent: "Organization" },
  { name: "SportsTeam", parent: "SportsOrganization" },
  { name: "WorkersUnion", parent: "Organization" },

  // ── Person ──
  { name: "Person", parent: "Thing", googleFeature: "Knowledge Panel", description: "A person (alive, dead, undead, or fictional)." },
  { name: "Patient", parent: "Person" },

  // ── Place ──
  { name: "Place", parent: "Thing", description: "Entities that have a somewhat fixed, physical extension." },
  { name: "Accommodation", parent: "Place" },
  { name: "Apartment", parent: "Accommodation" },
  { name: "CampingPitch", parent: "Accommodation" },
  { name: "House", parent: "Accommodation" },
  { name: "SingleFamilyResidence", parent: "House" },
  { name: "Room", parent: "Accommodation" },
  { name: "HotelRoom", parent: "Room" },
  { name: "MeetingRoom", parent: "Room" },
  { name: "Suite", parent: "Accommodation" },
  { name: "AdministrativeArea", parent: "Place" },
  { name: "City", parent: "AdministrativeArea" },
  { name: "Country", parent: "AdministrativeArea" },
  { name: "SchoolDistrict", parent: "AdministrativeArea" },
  { name: "State", parent: "AdministrativeArea" },
  { name: "ApartmentComplex", parent: "Place" },
  { name: "BoatTerminal", parent: "Place" },
  { name: "Bridge", parent: "Place" },
  { name: "BusStation", parent: "Place" },
  { name: "BusStop", parent: "Place" },
  { name: "Cemetery", parent: "Place" },
  { name: "CivicStructure", parent: "Place" },
  { name: "Airport", parent: "CivicStructure" },
  { name: "Aquarium", parent: "CivicStructure" },
  { name: "Beach", parent: "CivicStructure" },
  { name: "BuddhistTemple", parent: "CivicStructure" },
  { name: "CatholicChurch", parent: "CivicStructure" },
  { name: "Church", parent: "CivicStructure" },
  { name: "CityHall", parent: "CivicStructure" },
  { name: "Courthouse", parent: "CivicStructure" },
  { name: "Crematorium", parent: "CivicStructure" },
  { name: "DefenceEstablishment", parent: "CivicStructure" },
  { name: "Embassy", parent: "CivicStructure" },
  { name: "EventVenue", parent: "CivicStructure" },
  { name: "GovernmentBuilding", parent: "CivicStructure" },
  { name: "LegislativeBuilding", parent: "GovernmentBuilding" },
  { name: "HinduTemple", parent: "CivicStructure" },
  { name: "LandmarksOrHistoricalBuildings", parent: "CivicStructure" },
  { name: "Mosque", parent: "CivicStructure" },
  { name: "Museum", parent: "CivicStructure" },
  { name: "MusicVenue", parent: "CivicStructure" },
  { name: "Park", parent: "CivicStructure" },
  { name: "ParkingFacility", parent: "CivicStructure" },
  { name: "PerformingArtsTheater", parent: "CivicStructure" },
  { name: "PlaceOfWorship", parent: "CivicStructure" },
  { name: "Playground", parent: "CivicStructure" },
  { name: "PublicToilet", parent: "CivicStructure" },
  { name: "RVPark", parent: "CivicStructure" },
  { name: "StadiumOrArena", parent: "CivicStructure" },
  { name: "SubwayStation", parent: "CivicStructure" },
  { name: "Synagogue", parent: "CivicStructure" },
  { name: "TaxiStand", parent: "CivicStructure" },
  { name: "TrainStation", parent: "CivicStructure" },
  { name: "Zoo", parent: "CivicStructure" },
  { name: "Continent", parent: "Place" },
  { name: "GatedResidenceCommunity", parent: "Place" },
  { name: "Landform", parent: "Place" },
  { name: "BodyOfWater", parent: "Landform" },
  { name: "Canal", parent: "BodyOfWater" },
  { name: "LakeBodyOfWater", parent: "BodyOfWater" },
  { name: "OceanBodyOfWater", parent: "BodyOfWater" },
  { name: "Pond", parent: "BodyOfWater" },
  { name: "Reservoir", parent: "BodyOfWater" },
  { name: "RiverBodyOfWater", parent: "BodyOfWater" },
  { name: "SeaBodyOfWater", parent: "BodyOfWater" },
  { name: "Waterfall", parent: "BodyOfWater" },
  { name: "Mountain", parent: "Landform" },
  { name: "Volcano", parent: "Landform" },
  { name: "Residence", parent: "Place" },
  { name: "TouristAttraction", parent: "Place" },
  { name: "TouristDestination", parent: "Place" },
  { name: "VacationRental", parent: "Place" },

  // ── Product ──
  { name: "Product", parent: "Thing", googleFeature: "Product Rich Results", description: "Any offered product or service." },
  { name: "IndividualProduct", parent: "Product" },
  { name: "ProductGroup", parent: "Product" },
  { name: "ProductModel", parent: "Product" },
  { name: "SomeProducts", parent: "Product" },
  { name: "Vehicle", parent: "Product" },
  { name: "BusOrCoach", parent: "Vehicle" },
  { name: "Car", parent: "Vehicle" },
  { name: "Motorcycle", parent: "Vehicle" },
  { name: "MotorizedBicycle", parent: "Vehicle" },

  // ── DataType ──
  { name: "DataType", parent: "Thing" },
  { name: "Boolean", parent: "DataType" },
  { name: "Date", parent: "DataType" },
  { name: "DateTime", parent: "DataType" },
  { name: "Number", parent: "DataType" },
  { name: "Float", parent: "Number" },
  { name: "Integer", parent: "Number" },
  { name: "Text", parent: "DataType" },
  { name: "CssSelectorType", parent: "Text" },
  { name: "PronounceableText", parent: "Text" },
  { name: "URL", parent: "Text" },
  { name: "XPathType", parent: "Text" },
  { name: "Time", parent: "DataType" },

  // ── Other top-level under Thing ──
  { name: "EducationalOccupationalProgram", parent: "Intangible" },
  { name: "WorkBasedProgram", parent: "EducationalOccupationalProgram" },

  // ── Quantities ──
  { name: "Quantity", parent: "Intangible" },
  { name: "Distance", parent: "Quantity" },
  { name: "Duration", parent: "Quantity" },
  { name: "Energy", parent: "Quantity" },
  { name: "Mass", parent: "Quantity" },

  // ── Additional missing types from user's list ──
  { name: "Report", parent: "Article" },
  { name: "SocialMediaPosting", parent: "Article" },
  { name: "BlogPosting", parent: "SocialMediaPosting" },
  { name: "LiveBlogPosting", parent: "BlogPosting" },
  { name: "DiscussionForumPosting", parent: "SocialMediaPosting" },
  { name: "Periodical", parent: "CreativeWorkSeries" },
  { name: "Newspaper", parent: "Periodical" },
  { name: "PhysicalActivity", parent: "Thing" },
  { name: "ConstraintNode", parent: "Intangible" },
  { name: "Class", parent: "Intangible" },
  { name: "Skin", parent: "AnatomicalStructure" },
  { name: "Registry", parent: "Intangible" },
];

// Helper to build a tree from the flat list
export interface SchemaTreeNode {
  name: string;
  description?: string;
  googleFeature?: string;
  children: SchemaTreeNode[];
}

export function buildFullSchemaTree(): SchemaTreeNode {
  const nodeMap: Record<string, SchemaTreeNode> = {};
  const root: SchemaTreeNode = { name: "Thing", description: "The most generic type of item.", children: [] };
  nodeMap["Thing"] = root;

  // First pass: create all nodes
  FULL_SCHEMA_TYPES.forEach((t) => {
    if (!nodeMap[t.name]) {
      nodeMap[t.name] = { name: t.name, description: t.description, googleFeature: t.googleFeature, children: [] };
    } else {
      if (t.description) nodeMap[t.name].description = t.description;
      if (t.googleFeature) nodeMap[t.name].googleFeature = t.googleFeature;
    }
  });

  // Second pass: build hierarchy
  FULL_SCHEMA_TYPES.forEach((t) => {
    if (t.parent && t.name !== "Thing") {
      if (!nodeMap[t.parent]) {
        nodeMap[t.parent] = { name: t.parent, children: [] };
      }
      // Avoid duplicates
      if (!nodeMap[t.parent].children.find((c) => c.name === t.name)) {
        nodeMap[t.parent].children.push(nodeMap[t.name]);
      }
    }
  });

  // Sort children alphabetically
  const sortChildren = (node: SchemaTreeNode) => {
    node.children.sort((a, b) => a.name.localeCompare(b.name));
    node.children.forEach(sortChildren);
  };
  sortChildren(root);

  return root;
}

// Get all type names for search/autocomplete
export function getAllSchemaTypeNames(): string[] {
  return FULL_SCHEMA_TYPES.map((t) => t.name).sort();
}

// Get count of all types
export function getSchemaTypeCount(): number {
  return FULL_SCHEMA_TYPES.length;
}
