import { GoalStep } from "@/hooks/use-semantic-goals";

export interface GoalTemplate {
  key: string;
  name: string;
  description: string;
  goal_type: "niche_template" | "seo_objective" | "custom";
  icon: string;
  color: string;
  steps: GoalStep[];
}

let stepId = 0;
const s = (title: string, description: string, type: GoalStep["type"], target_entity_type?: string, target_count?: number): GoalStep => ({
  id: `step-${++stepId}`,
  title,
  description,
  type,
  target_entity_type,
  target_count,
  completed: false,
});

function resetId() { stepId = 0; }

// ────────────── NICHE TEMPLATES ──────────────
export const NICHE_TEMPLATES: GoalTemplate[] = [
  (() => { resetId(); return {
    key: "clinica_odonto",
    name: "Clínica Odontológica",
    description: "Grafo completo para clínicas odontológicas com profissionais, serviços, localização e avaliações.",
    goal_type: "niche_template" as const,
    icon: "Stethoscope",
    color: "#22c55e",
    steps: [
      s("Criar entidade da Clínica", "Crie a entidade principal do tipo 'empresa' representando sua clínica com nome, descrição e CNPJ", "entity", "empresa", 1),
      s("Adicionar Profissionais", "Crie pelo menos 3 entidades 'pessoa' para dentistas e especialistas com CRO", "entity", "pessoa", 3),
      s("Listar Serviços/Procedimentos", "Crie entidades 'servico' para cada procedimento (limpeza, implante, clareamento, ortodontia, endodontia)", "entity", "servico", 5),
      s("Definir Localização completa", "Crie entidade 'local' com endereço, CEP, bairro, cidade, estado e coordenadas", "entity", "local", 1),
      s("Adicionar Horários de Funcionamento", "Crie entidade 'horario' com dias e horários de atendimento", "entity", "horario", 1),
      s("Adicionar Avaliações/Reviews", "Crie entidade 'avaliacao' com rating agregado e contagem de avaliações", "entity", "avaliacao", 1),
      s("Criar Especialidades", "Entidades 'especialidade' (Ortodontia, Implantodontia, Periodontia)", "entity", "especialidade", 3),
      s("Adicionar Equipamentos/Tecnologias", "Entidades 'equipamento' para diferenciais (Raio-X 3D, Laser, Scanner)", "entity", "equipamento", 2),
      s("Criar relações profissional→clínica", "Conecte cada profissional à clínica com 'trabalha_em'", "relation"),
      s("Criar relações serviço→clínica", "Conecte serviços à clínica com 'oferece' ou 'presta'", "relation"),
      s("Vincular profissionais a especialidades", "Relação 'especialista_em' para cada dentista", "relation"),
      s("Conectar localização à clínica", "Relação 'localizado_em' com endereço completo", "relation"),
      s("Gerar Schema LocalBusiness > Dentist", "Gere o Schema.org do tipo Dentist com endereço, telefone e horários", "schema"),
      s("Gerar Schema Person para Profissionais", "Gere Schema Person com CRO, especialidade e sameAs", "schema"),
      s("Gerar Schema MedicalProcedure", "Schema para procedimentos com descrição e faixa de preço", "schema"),
      s("Implementar JSON-LD nas páginas", "Cole o código JSON-LD gerado em pelo menos 3 páginas do site", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "ecommerce_moda",
    name: "E-commerce de Moda",
    description: "Estrutura semântica para lojas virtuais de moda com produtos, marcas, categorias e ofertas.",
    goal_type: "niche_template" as const,
    icon: "ShoppingBag",
    color: "#ec4899",
    steps: [
      s("Criar entidade da Loja", "Entidade principal 'empresa' representando o e-commerce com CNPJ e descrição", "entity", "empresa", 1),
      s("Adicionar Marcas parceiras", "Crie entidades 'marca' para as principais marcas vendidas", "entity", "marca", 5),
      s("Criar Categorias do catálogo", "Entidades 'categoria' (Vestidos, Calçados, Bolsas, Acessórios, Roupas Masculinas)", "entity", "categoria", 5),
      s("Listar Produtos principais", "Crie pelo menos 8 entidades 'produto' com descrições ricas, preço e disponibilidade", "entity", "produto", 8),
      s("Adicionar Coleções/Lançamentos", "Entidades 'colecao' para coleções sazonais (Verão 2026, Inverno 2026)", "entity", "colecao", 2),
      s("Adicionar Ofertas ativas", "Entidades 'oferta' para promoções e cupons com datas de validade", "entity", "oferta", 3),
      s("Criar Materiais/Tecidos", "Entidades 'material' (Algodão, Seda, Couro, Poliéster)", "entity", "material", 3),
      s("Adicionar Tamanhos/Variantes", "Entidades 'variante' para grades de tamanho e cor", "entity", "variante", 2),
      s("Conectar Produtos a Categorias", "Use 'categorizado_em' para vincular cada produto", "relation"),
      s("Conectar Produtos a Marcas", "Use 'possui_marca' para vincular à marca fabricante", "relation"),
      s("Vincular Produtos a Coleções", "Relação 'faz_parte_de' para organizar por coleção", "relation"),
      s("Conectar Ofertas a Produtos", "Relação 'aplica_se_a' para vincular promoções", "relation"),
      s("Vincular Materiais a Produtos", "Relação 'feito_de' para composição de materiais", "relation"),
      s("Gerar Schema Product", "Gere Schema.org Product com preço, disponibilidade, imagem e reviews", "schema"),
      s("Gerar Schema Organization", "Schema da loja com logo, contato e políticas", "schema"),
      s("Gerar Schema BreadcrumbList", "Schema de navegação para páginas de categoria", "schema"),
      s("Gerar Schema Offer", "Schema com preço, validade e condições de cada oferta", "schema"),
      s("Implementar JSON-LD nas páginas de produto", "Cole o código nas 5 páginas de produto mais importantes", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "restaurante",
    name: "Restaurante / Delivery",
    description: "Grafo para restaurantes com cardápio, localização, horários e avaliações no Google.",
    goal_type: "niche_template" as const,
    icon: "UtensilsCrossed",
    color: "#f97316",
    steps: [
      s("Criar entidade do Restaurante", "Entidade 'empresa' com nome, descrição, tipo de cozinha e CNPJ", "entity", "empresa", 1),
      s("Adicionar Localização completa", "Entidade 'local' com endereço, bairro, CEP e coordenadas", "entity", "local", 1),
      s("Definir Horários de Funcionamento", "Entidade 'horario' com horários por dia da semana (incluindo feriados)", "entity", "horario", 1),
      s("Listar Pratos Principais", "Entidades 'produto' para pratos do cardápio com descrição e preço", "entity", "produto", 8),
      s("Criar Categorias do Cardápio", "Entidades 'categoria' (Entradas, Pratos Principais, Sobremesas, Bebidas, Combos)", "entity", "categoria", 5),
      s("Adicionar Chef/Proprietário", "Entidade 'pessoa' para o chef ou proprietário com biografia", "entity", "pessoa", 1),
      s("Adicionar Avaliações", "Entidade 'avaliacao' com rating agregado, contagem e plataforma (Google, iFood)", "entity", "avaliacao", 1),
      s("Criar Tipos de Cozinha", "Entidades 'culinaria' (Italiana, Japonesa, Brasileira, etc.)", "entity", "culinaria", 2),
      s("Adicionar Formas de Pagamento", "Entidade 'pagamento' com métodos aceitos (Pix, cartão, VR)", "entity", "pagamento", 1),
      s("Conectar Pratos a Categorias", "Relação 'categorizado_em' para cada prato", "relation"),
      s("Conectar Localização ao Restaurante", "Relação 'localizado_em' com endereço", "relation"),
      s("Vincular Chef ao Restaurante", "Relação 'chef_de' ou 'proprietario_de'", "relation"),
      s("Gerar Schema Restaurant", "Schema.org Restaurant com cardápio, horários e endereço", "schema"),
      s("Gerar Schema Menu / MenuItem", "Schema para cada prato com preço e descrição", "schema"),
      s("Gerar Schema AggregateRating", "Schema de avaliações com nota e contagem", "schema"),
      s("Implementar JSON-LD no site", "Cole o código nas páginas do site e Google Meu Negócio", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "escritorio_advocacia",
    name: "Escritório de Advocacia",
    description: "Estrutura para escritórios jurídicos com advogados, áreas de atuação e credenciais.",
    goal_type: "niche_template" as const,
    icon: "Scale",
    color: "#6366f1",
    steps: [
      s("Criar entidade do Escritório", "Entidade 'empresa' com razão social, CNPJ e descrição do escritório", "entity", "empresa", 1),
      s("Adicionar Advogados/Sócios", "Entidades 'pessoa' para cada advogado com biografia e OAB", "entity", "pessoa", 3),
      s("Listar Áreas de Atuação", "Entidades 'servico' detalhadas (Direito Civil, Trabalhista, Tributário, Penal, Família)", "entity", "servico", 5),
      s("Adicionar Credenciais OAB", "Entidades 'credencial' com números da OAB e seção", "entity", "credencial", 3),
      s("Criar Artigos/Publicações", "Entidades 'artigo' para conteúdo jurídico publicado com data e tema", "entity", "artigo", 3),
      s("Adicionar Casos de Sucesso", "Entidades 'caso' para resultados relevantes (anonimizados)", "entity", "caso", 2),
      s("Definir Localização", "Entidade 'local' com endereço do escritório e filiais", "entity", "local", 1),
      s("Adicionar Formação Acadêmica", "Entidades 'formacao' para universidades e pós-graduações", "entity", "formacao", 2),
      s("Conectar advogados ao escritório", "Relação 'trabalha_em' ou 'socio_de'", "relation"),
      s("Vincular credenciais a advogados", "Relação 'possui_credencial' para OAB", "relation"),
      s("Conectar advogados a áreas", "Relação 'especialista_em' para cada área de atuação", "relation"),
      s("Vincular artigos a autores", "Relação 'escrito_por' para publicações", "relation"),
      s("Gerar Schema LegalService", "Schema do escritório com áreas de atuação", "schema"),
      s("Gerar Schema Person + Credential", "Schema Person com OAB, formação e knowsAbout", "schema"),
      s("Gerar Schema Article", "Schema Article com author, datePublished e speakable", "schema"),
      s("Implementar JSON-LD no site", "Cole schemas em páginas do escritório, equipe e blog", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "imobiliaria",
    name: "Imobiliária / Corretor",
    description: "Grafo para imobiliárias com imóveis, localizações, agentes e avaliações.",
    goal_type: "niche_template" as const,
    icon: "Home",
    color: "#06b6d4",
    steps: [
      s("Criar entidade da Imobiliária", "Entidade 'empresa' com CRECI, descrição e diferenciais", "entity", "empresa", 1),
      s("Adicionar Corretores", "Entidades 'pessoa' para agentes com CRECI e áreas de atuação", "entity", "pessoa", 3),
      s("Listar Imóveis à Venda", "Entidades 'produto' para imóveis à venda com metragem, quartos e valor", "entity", "produto", 5),
      s("Listar Imóveis para Locação", "Entidades 'produto' para imóveis de locação com valor e condições", "entity", "produto", 3),
      s("Definir Bairros/Regiões", "Entidades 'local' para cada bairro ou região de atuação", "entity", "local", 3),
      s("Criar Tipos de Imóvel", "Entidades 'tipo' (Apartamento, Casa, Terreno, Comercial, Cobertura)", "entity", "tipo", 4),
      s("Adicionar Ofertas e Condições", "Entidades 'oferta' com valores, financiamento e condições", "entity", "oferta", 3),
      s("Adicionar Empreendimentos", "Entidades 'empreendimento' para lançamentos na planta", "entity", "empreendimento", 2),
      s("Conectar imóveis a locais", "Relação 'localizado_em' com bairro/região", "relation"),
      s("Vincular corretores a imóveis", "Relação 'responsavel_por' para cada corretor", "relation"),
      s("Conectar imóveis a tipos", "Relação 'tipo_de' (apartamento, casa, etc.)", "relation"),
      s("Vincular ofertas a imóveis", "Relação 'refere_se_a' para condições de venda/aluguel", "relation"),
      s("Gerar Schema RealEstateAgent", "Schema.org da imobiliária com contatos e CRECI", "schema"),
      s("Gerar Schema Residence/Apartment", "Schema para cada imóvel com preço e características", "schema"),
      s("Gerar Schema Place para bairros", "Schema de localização para áreas de atuação", "schema"),
      s("Implementar JSON-LD", "Cole schemas nas páginas de imóveis e sobre a imobiliária", "custom"),
    ],
  }; })(),

  // ────────── NEW TEMPLATES ──────────

  (() => { resetId(); return {
    key: "clinica_medica",
    name: "Clínica Médica / Hospital",
    description: "Grafo para clínicas e hospitais com médicos, especialidades, exames e convênios.",
    goal_type: "niche_template" as const,
    icon: "Stethoscope",
    color: "#10b981",
    steps: [
      s("Criar entidade da Clínica/Hospital", "Entidade 'empresa' com CNES, descrição e tipo de estabelecimento", "entity", "empresa", 1),
      s("Adicionar Médicos", "Entidades 'pessoa' para cada médico com CRM e especialidade", "entity", "pessoa", 4),
      s("Listar Especialidades Médicas", "Entidades 'especialidade' (Cardiologia, Ortopedia, Dermatologia, etc.)", "entity", "especialidade", 5),
      s("Adicionar Exames e Procedimentos", "Entidades 'exame' para exames oferecidos (ECG, Raio-X, etc.)", "entity", "exame", 4),
      s("Listar Convênios aceitos", "Entidades 'convenio' para planos de saúde aceitos", "entity", "convenio", 3),
      s("Definir Localização e Unidades", "Entidades 'local' para cada unidade com endereço completo", "entity", "local", 1),
      s("Adicionar Horários", "Entidade 'horario' com funcionamento e plantão", "entity", "horario", 1),
      s("Adicionar Equipamentos", "Entidades 'equipamento' para diferenciais tecnológicos", "entity", "equipamento", 2),
      s("Conectar médicos à clínica", "Relação 'atende_em' para cada profissional", "relation"),
      s("Vincular médicos a especialidades", "Relação 'especialista_em'", "relation"),
      s("Conectar exames à clínica", "Relação 'realiza' para exames", "relation"),
      s("Vincular convênios", "Relação 'aceita_convenio' para planos de saúde", "relation"),
      s("Gerar Schema MedicalClinic", "Schema.org com médicos, especialidades e contatos", "schema"),
      s("Gerar Schema Physician", "Schema para cada médico com CRM e especialidade", "schema"),
      s("Gerar Schema MedicalTest", "Schema para exames oferecidos", "schema"),
      s("Implementar JSON-LD", "Cole os schemas nas páginas do site", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "academia_fitness",
    name: "Academia / Personal Trainer",
    description: "Grafo para academias e personal trainers com modalidades, professores e estrutura.",
    goal_type: "niche_template" as const,
    icon: "Award",
    color: "#f59e0b",
    steps: [
      s("Criar entidade da Academia", "Entidade 'empresa' com nome, descrição e diferenciais", "entity", "empresa", 1),
      s("Adicionar Professores/Trainers", "Entidades 'pessoa' para personal trainers e instrutores com CREF", "entity", "pessoa", 3),
      s("Listar Modalidades", "Entidades 'servico' (Musculação, CrossFit, Yoga, Pilates, Funcional, Spinning)", "entity", "servico", 6),
      s("Criar Planos/Pacotes", "Entidades 'oferta' com preços e benefícios de cada plano", "entity", "oferta", 3),
      s("Adicionar Estrutura/Equipamentos", "Entidades 'equipamento' para espaços e aparelhos disponíveis", "entity", "equipamento", 3),
      s("Definir Localização", "Entidade 'local' com endereço e estacionamento", "entity", "local", 1),
      s("Adicionar Horários", "Entidade 'horario' com grade de aulas e funcionamento", "entity", "horario", 1),
      s("Adicionar Avaliações", "Entidade 'avaliacao' com rating e depoimentos", "entity", "avaliacao", 1),
      s("Conectar professores à academia", "Relação 'trabalha_em' para cada profissional", "relation"),
      s("Vincular modalidades a professores", "Relação 'ministra' para cada aula", "relation"),
      s("Conectar planos à academia", "Relação 'oferece' para cada pacote", "relation"),
      s("Gerar Schema SportsActivityLocation", "Schema da academia com modalidades e contatos", "schema"),
      s("Gerar Schema Person para trainers", "Schema com CREF e especialidades", "schema"),
      s("Implementar JSON-LD", "Cole schemas no site e landing pages", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "escola_cursos",
    name: "Escola / Cursos Online",
    description: "Grafo para instituições de ensino e plataformas de cursos com professores, disciplinas e certificações.",
    goal_type: "niche_template" as const,
    icon: "BookOpen",
    color: "#3b82f6",
    steps: [
      s("Criar entidade da Instituição", "Entidade 'empresa' com nome, descrição e credenciamentos (MEC)", "entity", "empresa", 1),
      s("Adicionar Professores/Instrutores", "Entidades 'pessoa' com titulação e área de conhecimento", "entity", "pessoa", 4),
      s("Listar Cursos oferecidos", "Entidades 'curso' com carga horária, nível e pré-requisitos", "entity", "curso", 6),
      s("Criar Categorias/Áreas", "Entidades 'categoria' (Tecnologia, Negócios, Design, Marketing, Saúde)", "entity", "categoria", 4),
      s("Adicionar Certificações", "Entidades 'certificacao' para certificados e diplomas emitidos", "entity", "certificacao", 2),
      s("Definir Modalidades", "Entidades 'modalidade' (Presencial, EAD, Híbrido, Ao Vivo)", "entity", "modalidade", 3),
      s("Adicionar Depoimentos", "Entidades 'avaliacao' com depoimentos de alunos", "entity", "avaliacao", 2),
      s("Criar Trilhas de Aprendizado", "Entidades 'trilha' agrupando cursos em sequência lógica", "entity", "trilha", 2),
      s("Conectar professores a cursos", "Relação 'ministra' para cada instrutor", "relation"),
      s("Vincular cursos a categorias", "Relação 'categorizado_em' por área de conhecimento", "relation"),
      s("Conectar certificações a cursos", "Relação 'certifica' ao concluir", "relation"),
      s("Vincular cursos a trilhas", "Relação 'faz_parte_de' para cada trilha", "relation"),
      s("Gerar Schema Course", "Schema.org Course com provider, duration e rating", "schema"),
      s("Gerar Schema EducationalOrganization", "Schema da instituição com credenciamentos", "schema"),
      s("Gerar Schema Person para professores", "Schema com titulação e sameAs", "schema"),
      s("Implementar JSON-LD", "Cole schemas nas páginas de cursos e sobre nós", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "saas_tecnologia",
    name: "SaaS / Empresa de Tecnologia",
    description: "Grafo para empresas de software com produtos, funcionalidades, integrações e equipe.",
    goal_type: "niche_template" as const,
    icon: "Layers",
    color: "#8b5cf6",
    steps: [
      s("Criar entidade da Empresa", "Entidade 'empresa' com descrição, missão e segmento de atuação", "entity", "empresa", 1),
      s("Adicionar Produtos/Plataformas", "Entidades 'produto' para cada software oferecido", "entity", "produto", 2),
      s("Listar Funcionalidades", "Entidades 'funcionalidade' para features do produto (Dashboard, API, Reports)", "entity", "funcionalidade", 6),
      s("Criar Planos/Pricing", "Entidades 'oferta' para cada tier de preço (Free, Pro, Enterprise)", "entity", "oferta", 3),
      s("Adicionar Integrações", "Entidades 'integracao' para APIs e conectores (Slack, Zapier, Google)", "entity", "integracao", 4),
      s("Definir Casos de Uso", "Entidades 'caso_uso' para segmentos-alvo (Marketing, Vendas, RH)", "entity", "caso_uso", 3),
      s("Adicionar Equipe/Fundadores", "Entidades 'pessoa' para fundadores e líderes técnicos", "entity", "pessoa", 2),
      s("Criar Documentação/Artigos", "Entidades 'artigo' para blog posts e docs técnicos", "entity", "artigo", 3),
      s("Conectar funcionalidades a produtos", "Relação 'possui_feature' para cada recurso", "relation"),
      s("Vincular planos a produtos", "Relação 'disponivel_em' para tiers", "relation"),
      s("Conectar integrações", "Relação 'integra_com' para cada conector", "relation"),
      s("Vincular equipe à empresa", "Relação 'fundador_de' ou 'CTO_de'", "relation"),
      s("Gerar Schema SoftwareApplication", "Schema com features, pricing e sistema operacional", "schema"),
      s("Gerar Schema Organization", "Schema com fundadores, logo e contatos", "schema"),
      s("Gerar Schema FAQPage", "Schema para página de perguntas frequentes", "schema"),
      s("Implementar JSON-LD", "Cole schemas no site, pricing e docs", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "agencia_marketing",
    name: "Agência de Marketing Digital",
    description: "Grafo para agências de marketing com serviços, portfólio, equipe e cases de sucesso.",
    goal_type: "niche_template" as const,
    icon: "Award",
    color: "#f43f5e",
    steps: [
      s("Criar entidade da Agência", "Entidade 'empresa' com nome, descrição, fundação e posicionamento", "entity", "empresa", 1),
      s("Listar Serviços oferecidos", "Entidades 'servico' (SEO, Tráfego Pago, Branding, Social Media, Conteúdo, Web Design)", "entity", "servico", 6),
      s("Adicionar Equipe/Especialistas", "Entidades 'pessoa' para sócios e líderes de equipe", "entity", "pessoa", 3),
      s("Criar Cases de Sucesso", "Entidades 'caso' com resultados mensuráveis de clientes", "entity", "caso", 3),
      s("Adicionar Certificações", "Entidades 'certificacao' (Google Partner, Meta Blueprint, HubSpot)", "entity", "certificacao", 3),
      s("Listar Ferramentas utilizadas", "Entidades 'ferramenta' (SEMrush, Analytics, Ads, etc.)", "entity", "ferramenta", 4),
      s("Definir Segmentos atendidos", "Entidades 'segmento' (E-commerce, B2B, Saúde, Educação)", "entity", "segmento", 3),
      s("Adicionar Localização", "Entidade 'local' com endereço e áreas de atendimento", "entity", "local", 1),
      s("Conectar serviços à agência", "Relação 'oferece' para cada serviço", "relation"),
      s("Vincular equipe a serviços", "Relação 'lidera' ou 'responsavel_por'", "relation"),
      s("Conectar cases a serviços", "Relação 'utilizou' para demonstrar resultados", "relation"),
      s("Vincular certificações à agência", "Relação 'certificado_por' para autoridade", "relation"),
      s("Gerar Schema ProfessionalService", "Schema da agência com serviços e contatos", "schema"),
      s("Gerar Schema Person para equipe", "Schema com cargo, especialidade e redes sociais", "schema"),
      s("Gerar Schema Article para cases", "Schema com resultados e métricas", "schema"),
      s("Implementar JSON-LD", "Cole schemas no site, portfólio e equipe", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "pet_shop",
    name: "Pet Shop / Veterinária",
    description: "Grafo para pet shops e clínicas veterinárias com serviços, produtos e profissionais.",
    goal_type: "niche_template" as const,
    icon: "Stethoscope",
    color: "#a855f7",
    steps: [
      s("Criar entidade do Pet Shop", "Entidade 'empresa' com nome, descrição e tipo (loja, clínica ou ambos)", "entity", "empresa", 1),
      s("Adicionar Veterinários", "Entidades 'pessoa' para veterinários com CRMV e especialidade", "entity", "pessoa", 2),
      s("Listar Serviços", "Entidades 'servico' (Consulta, Banho, Tosa, Vacinação, Cirurgia, Hospedagem)", "entity", "servico", 6),
      s("Criar Categorias de Produtos", "Entidades 'categoria' (Ração, Brinquedos, Medicamentos, Acessórios)", "entity", "categoria", 4),
      s("Adicionar Espécies atendidas", "Entidades 'especie' (Cães, Gatos, Aves, Roedores)", "entity", "especie", 3),
      s("Definir Localização", "Entidade 'local' com endereço e estacionamento", "entity", "local", 1),
      s("Adicionar Horários", "Entidade 'horario' com plantão 24h se aplicável", "entity", "horario", 1),
      s("Adicionar Avaliações", "Entidade 'avaliacao' com rating e depoimentos de tutores", "entity", "avaliacao", 1),
      s("Conectar serviços ao pet shop", "Relação 'oferece' para cada serviço", "relation"),
      s("Vincular veterinários à clínica", "Relação 'atende_em'", "relation"),
      s("Conectar espécies a serviços", "Relação 'atende_especie' para cada serviço", "relation"),
      s("Gerar Schema VeterinaryCare", "Schema.org com serviços, localização e contatos", "schema"),
      s("Gerar Schema Person para vets", "Schema com CRMV e especialidade", "schema"),
      s("Implementar JSON-LD", "Cole schemas no site e Google Meu Negócio", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "hotel_pousada",
    name: "Hotel / Pousada",
    description: "Grafo para hotéis e pousadas com quartos, comodidades, localização e avaliações.",
    goal_type: "niche_template" as const,
    icon: "Home",
    color: "#0ea5e9",
    steps: [
      s("Criar entidade do Hotel", "Entidade 'empresa' com estrelas, descrição e diferenciais", "entity", "empresa", 1),
      s("Listar Tipos de Quarto", "Entidades 'produto' (Standard, Luxo, Suíte, Família, Acessível)", "entity", "produto", 4),
      s("Adicionar Comodidades", "Entidades 'comodidade' (Piscina, Spa, Wi-Fi, Estacionamento, Restaurante)", "entity", "comodidade", 5),
      s("Definir Localização detalhada", "Entidade 'local' com endereço, bairro, pontos turísticos próximos", "entity", "local", 1),
      s("Adicionar Tarifas e Pacotes", "Entidades 'oferta' com preços por temporada e pacotes especiais", "entity", "oferta", 3),
      s("Criar Atrações próximas", "Entidades 'atracao' para pontos turísticos e atividades na região", "entity", "atracao", 3),
      s("Adicionar Avaliações", "Entidade 'avaliacao' com notas de múltiplas plataformas (Google, Booking, TripAdvisor)", "entity", "avaliacao", 1),
      s("Adicionar Políticas", "Entidades 'politica' (Check-in, Cancelamento, Pets, Fumantes)", "entity", "politica", 2),
      s("Conectar quartos ao hotel", "Relação 'oferece' com preços e disponibilidade", "relation"),
      s("Vincular comodidades", "Relação 'possui' para cada facilidade", "relation"),
      s("Conectar atrações à localização", "Relação 'proximo_a' com distâncias", "relation"),
      s("Gerar Schema LodgingBusiness", "Schema com quartos, tarifas e classificação", "schema"),
      s("Gerar Schema HotelRoom", "Schema para cada tipo de quarto", "schema"),
      s("Gerar Schema AggregateRating", "Schema de avaliações consolidadas", "schema"),
      s("Implementar JSON-LD", "Cole schemas nas páginas de quartos, reservas e sobre", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "contabilidade",
    name: "Escritório de Contabilidade",
    description: "Grafo para contadores e escritórios contábeis com serviços, equipe e certificações.",
    goal_type: "niche_template" as const,
    icon: "Scale",
    color: "#14b8a6",
    steps: [
      s("Criar entidade do Escritório", "Entidade 'empresa' com CRC, descrição e segmentos atendidos", "entity", "empresa", 1),
      s("Adicionar Contadores", "Entidades 'pessoa' para contadores com CRC e especialização", "entity", "pessoa", 3),
      s("Listar Serviços Contábeis", "Entidades 'servico' (Abertura de Empresa, Imposto de Renda, Folha, BPO, Fiscal)", "entity", "servico", 6),
      s("Criar Segmentos Atendidos", "Entidades 'segmento' (MEI, Simples, Lucro Presumido, Lucro Real)", "entity", "segmento", 4),
      s("Adicionar Certificações", "Entidades 'certificacao' (CRC, CPA, especialização tributária)", "entity", "certificacao", 2),
      s("Definir Localização", "Entidade 'local' com endereço do escritório", "entity", "local", 1),
      s("Adicionar Artigos Fiscais", "Entidades 'artigo' para conteúdo sobre legislação e impostos", "entity", "artigo", 3),
      s("Conectar contadores ao escritório", "Relação 'trabalha_em' com cargo", "relation"),
      s("Vincular serviços a segmentos", "Relação 'atende' para cada regime tributário", "relation"),
      s("Conectar certificações", "Relação 'possui_certificacao'", "relation"),
      s("Gerar Schema AccountingService", "Schema com serviços, equipe e contatos", "schema"),
      s("Gerar Schema Person para contadores", "Schema com CRC e knowsAbout", "schema"),
      s("Implementar JSON-LD", "Cole schemas no site e páginas de serviços", "custom"),
    ],
  }; })(),
];

// ────────────── SEO OBJECTIVES ──────────────
export const SEO_OBJECTIVES: GoalTemplate[] = [
  (() => { resetId(); return {
    key: "knowledge_panel",
    name: "Aparecer no Knowledge Panel",
    description: "Construa autoridade semântica suficiente para o Google gerar um Knowledge Panel da sua marca.",
    goal_type: "seo_objective" as const,
    icon: "Award",
    color: "#eab308",
    steps: [
      s("Entidade principal com descrição rica", "A empresa precisa de descrição detalhada com mais de 100 palavras, missão e história", "entity", "empresa", 1),
      s("Criar pelo menos 15 entidades conectadas", "Mínimo de 15 nós no grafo para demonstrar cobertura ampla", "entity", undefined, 15),
      s("Ter pelo menos 20 relações", "Rede densa de conexões entre entidades (mínimo 1.5x por entidade)", "relation"),
      s("Schema Organization completo", "Gere Schema com logo, fundadores, URL, redes sociais e endereço", "schema"),
      s("Adicionar perfis oficiais", "Entidades 'site' para Wikipedia, LinkedIn, Crunchbase, Instagram", "entity", "site", 4),
      s("Vincular fundadores/CEO", "Entidades 'pessoa' para cada fundador conectado à empresa com 'fundado_por'", "entity", "pessoa", 2),
      s("Criar entidades de prêmios/reconhecimentos", "Entidades 'premio' para certificações e reconhecimentos do mercado", "entity", "premio", 2),
      s("Adicionar marcos históricos", "Entidades 'evento' para datas importantes da empresa (fundação, expansão, IPO)", "entity", "evento", 3),
      s("Vincular tudo à entidade principal", "Cada entidade deve estar conectada direta ou indiretamente à empresa", "relation"),
      s("Implementar Schema em todas as páginas", "Gere e implemente JSON-LD em pelo menos 8 páginas do site", "schema"),
      s("Adicionar sameAs para referências externas", "Propriedade sameAs no Schema linkando para perfis oficiais", "schema"),
      s("Validar Schema no Google Rich Results", "Teste o Schema gerado no Rich Results Test do Google", "custom"),
      s("Enviar para indexação no GSC", "Após implementar, peça indexação no Google Search Console", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "entity_pack",
    name: "Dominar Entity Pack do Google",
    description: "Otimize para aparecer nos pacotes de entidades (carrosséis, listas) dos resultados de busca.",
    goal_type: "seo_objective" as const,
    icon: "Layers",
    color: "#8b5cf6",
    steps: [
      s("Mapear todas as entidades do seu segmento", "Identifique e crie pelo menos 12 entidades relevantes do nicho", "entity", undefined, 12),
      s("Criar relações hierárquicas", "Use 'parte_de', 'categorizado_em', 'tipo_de' para criar hierarquia clara", "relation"),
      s("Criar relações de comparação", "Use 'similar_a', 'alternativa_para' para posicionar entre concorrentes", "relation"),
      s("Cobrir todos os tipos de Schema", "Cada entidade deve ter Schema.org específico e descritivo", "schema"),
      s("Adicionar FAQs do nicho", "Crie pelo menos 5 entidades 'faq' para perguntas frequentes do segmento", "entity", "faq", 5),
      s("Adicionar Eventos do segmento", "Crie entidades 'evento' para feiras, conferências e datas sazonais", "entity", "evento", 2),
      s("Criar entidades de comparação", "Entidades que posicionem seu produto vs alternativas", "entity", "comparacao", 2),
      s("Mapear termos/glossário do nicho", "Entidades 'termo' para palavras-chave e definições do segmento", "entity", "termo", 5),
      s("Gerar Schema FAQPage", "Implemente FAQPage Schema nas páginas de perguntas", "schema"),
      s("Gerar Schema ItemList", "Schema para listas e comparações entre produtos", "schema"),
      s("Gerar Schema HowTo", "Schema para tutoriais e guias do segmento", "schema"),
      s("Análise de concorrentes", "Use a aba Concorrentes para identificar gaps de Schema", "custom"),
      s("Validar e implementar tudo", "Teste no Rich Results e cole nas páginas do site", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "local_seo",
    name: "SEO Local Completo",
    description: "Domine a busca local com entidades geográficas, GBP otimizado e reviews estruturados.",
    goal_type: "seo_objective" as const,
    icon: "MapPin",
    color: "#f43f5e",
    steps: [
      s("Configurar entidade GBP", "Crie entidade 'gbp' com ID do Google Business Profile", "entity", "gbp", 1),
      s("Adicionar Endereço completo", "Entidade 'endereco' com CEP, rua, número, complemento, bairro, cidade, estado", "entity", "endereco", 1),
      s("Coordenadas geográficas", "Entidade 'geo' com latitude/longitude exatos", "entity", "geo", 1),
      s("Horários de funcionamento detalhados", "Entidade 'horario' por dia da semana (incluindo feriados e exceções)", "entity", "horario", 1),
      s("Avaliações estruturadas", "Entidades 'rating' com notas, contagem e plataformas (Google, Facebook)", "entity", "rating", 2),
      s("Áreas de atendimento", "Entidades 'local' para todos os bairros e cidades atendidas", "entity", "local", 5),
      s("Adicionar Fotos do negócio", "Entidades 'midia' para fotos da fachada, interior e equipe", "entity", "midia", 3),
      s("Criar categorias de negócio", "Entidades para categoria principal e categorias secundárias do GBP", "entity", "categoria", 3),
      s("Adicionar NAP (Nome, Endereço, Telefone)", "Garanta consistência de NAP em todas as entidades", "entity", "contato", 1),
      s("Conectar tudo ao negócio", "Cada entidade de localização conectada à empresa", "relation"),
      s("Vincular áreas de atendimento", "Relação 'atende_regiao' para cada local", "relation"),
      s("Gerar Schema LocalBusiness", "Schema completo com endereço, horário, geo e contatos", "schema"),
      s("Gerar Schema GeoCoordinates", "Coordenadas precisas no schema do negócio", "schema"),
      s("Gerar Schema PostalAddress", "Endereço estruturado no padrão Schema", "schema"),
      s("Gerar Schema OpeningHoursSpecification", "Horários por dia no formato Schema", "schema"),
      s("Implementar em Google Meu Negócio", "Otimize o GBP com as informações do grafo", "custom"),
      s("Criar citações locais (NAP)", "Garanta NAP consistente em diretórios locais", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "content_authority",
    name: "Autoridade de Conteúdo (E-E-A-T)",
    description: "Construa E-E-A-T (Experience, Expertise, Authoritativeness, Trust) com entidades de autor e credenciais.",
    goal_type: "seo_objective" as const,
    icon: "BookOpen",
    color: "#22c55e",
    steps: [
      s("Criar autores com biografias completas", "Entidades 'pessoa' com descrições ricas, experiência e credenciais", "entity", "pessoa", 3),
      s("Adicionar credenciais profissionais", "Entidades 'credencial' para certificações, diplomas e registros", "entity", "credencial", 3),
      s("Criar formações acadêmicas", "Entidades 'formacao' para universidades e especializações", "entity", "formacao", 3),
      s("Adicionar experiências profissionais", "Entidades 'experiencia' com empresas e cargos anteriores", "entity", "experiencia", 3),
      s("Criar artigos vinculados", "Entidades 'artigo' conectadas aos autores (mínimo 8)", "entity", "artigo", 8),
      s("Organizar por pilares de conteúdo", "Categorize artigos em 4+ pilares temáticos", "entity", "categoria", 4),
      s("Adicionar prêmios/reconhecimentos", "Entidades 'premio' para reconhecimentos dos autores", "entity", "premio", 2),
      s("Criar citações/publicações externas", "Entidades 'publicacao_externa' para guest posts e mídia", "entity", "publicacao_externa", 3),
      s("Vincular autores a artigos", "Relação 'é_autor_de' para cada publicação", "relation"),
      s("Conectar credenciais a autores", "Relação 'possui_credencial' com datas", "relation"),
      s("Vincular formações a autores", "Relação 'formado_em' para cada instituição", "relation"),
      s("Conectar artigos a categorias", "Relação 'categorizado_em' por pilar", "relation"),
      s("Gerar Schema Article completo", "Schema com author, datePublished, publisher e speakable", "schema"),
      s("Gerar Schema Person detalhado", "Schema Person com sameAs, knowsAbout e credentials", "schema"),
      s("Gerar Schema AboutPage", "Schema da página sobre nós com equipe editorial", "schema"),
      s("Implementar Schema de Autor nas páginas", "JSON-LD de autor em cada post do blog", "custom"),
      s("Validar no Rich Results Test", "Teste todos os schemas no Google Rich Results Test", "custom"),
    ],
  }; })(),

  (() => { resetId(); return {
    key: "ecommerce_seo",
    name: "SEO para E-commerce",
    description: "Maximize a visibilidade de produtos com Rich Snippets, ofertas e avaliações estruturadas.",
    goal_type: "seo_objective" as const,
    icon: "ShoppingBag",
    color: "#ec4899",
    steps: [
      s("Criar entidade da Loja", "Entidade 'empresa' com políticas, contato e descrição", "entity", "empresa", 1),
      s("Mapear produtos principais", "Pelo menos 10 entidades 'produto' com descrições ricas", "entity", "produto", 10),
      s("Criar categorias hierárquicas", "Entidades 'categoria' em pelo menos 2 níveis de profundidade", "entity", "categoria", 6),
      s("Adicionar marcas", "Entidades 'marca' para cada fabricante relevante", "entity", "marca", 4),
      s("Criar ofertas e promoções", "Entidades 'oferta' com preço, validade e condições", "entity", "oferta", 3),
      s("Adicionar avaliações de produtos", "Entidades 'avaliacao' com rating por produto", "entity", "avaliacao", 3),
      s("Criar variações de produto", "Entidades 'variante' para tamanhos, cores e modelos", "entity", "variante", 3),
      s("Adicionar FAQs de produtos", "Entidades 'faq' para dúvidas frequentes dos clientes", "entity", "faq", 5),
      s("Conectar tudo com relações", "Vincular produtos, categorias, marcas e ofertas", "relation"),
      s("Criar breadcrumb semântico", "Relações hierárquicas entre categorias", "relation"),
      s("Gerar Schema Product com Offer", "Schema completo com preço, disponibilidade e condição", "schema"),
      s("Gerar Schema BreadcrumbList", "Schema de navegação para cada categoria", "schema"),
      s("Gerar Schema AggregateRating", "Schema de avaliações por produto", "schema"),
      s("Gerar Schema FAQPage", "Schema para perguntas de cada produto", "schema"),
      s("Gerar Schema Organization", "Schema da loja com logo, contato e políticas", "schema"),
      s("Implementar JSON-LD em produtos", "Cole schema em todas as páginas de produto", "custom"),
      s("Validar Rich Snippets", "Teste produtos no Rich Results e busca do Google", "custom"),
    ],
  }; })(),
];

export const ALL_TEMPLATES = [...NICHE_TEMPLATES, ...SEO_OBJECTIVES];
